# Generated by Django 5.2.16 on 2026-07-12

import django.db.models.deletion
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_capability_grants"),
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name="BuildingLocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("active", models.BooleanField(default=True)),
                ("building", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="accounts.building")),
                ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="maintenance.buildinglocation")),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("building", "parent", "name"), name="location_sibling_name_once", nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name="IssueReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                ("location_path_snapshot", models.CharField(max_length=1000)),
                ("status", models.CharField(choices=[("OPEN", "Open"), ("RESOLVED", "Resolved")], default="OPEN", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reporter", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ("selected_location", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="maintenance.buildinglocation")),
                ("unit", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="accounts.unit")),
            ],
        ),
        migrations.CreateModel(
            name="TriageJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("PROCESSING", "Processing"), ("SUCCEEDED", "Succeeded"), ("NEEDS_MANUAL", "Needs manual triage")], default="PENDING", max_length=16)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("report", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="triage_job", to="maintenance.issuereport")),
            ],
        ),
        migrations.CreateModel(
            name="TriageSuggestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category", models.CharField(max_length=128)),
                ("interpreted_location", models.CharField(max_length=1000)),
                ("urgency", models.CharField(max_length=16)),
                ("confidence_percent", models.PositiveSmallIntegerField()),
                ("duplicate_report_ids", models.JSONField(default=list)),
                ("department", models.CharField(max_length=128)),
                ("deadline_minutes", models.PositiveIntegerField()),
                ("raw_response", models.JSONField()),
                ("provider_request_id", models.CharField(max_length=255)),
                ("validation_metadata", models.JSONField(default=dict)),
                ("elapsed_ms", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("job", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="suggestion", to="maintenance.triagejob")),
            ],
        ),
        migrations.CreateModel(
            name="ReportPhoto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("report", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="photos", to="maintenance.issuereport")),
                ("version", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="documents.documentversion")),
            ],
            options={"constraints": [models.UniqueConstraint(fields=("report", "version"), name="report_photo_once")]},
        ),
    ]
