# Generated by Django 5.2.16 on 2026-07-13 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_capability_grants'),
        ('documents', '0001_initial'),
        ('maintenance', '0003_prevent_location_building_changes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grouped_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_reports', to='maintenance.issuereport')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=128)),
                ('urgency', models.CharField(max_length=16)),
                ('department', models.CharField(max_length=128)),
                ('deadline_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.building')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.buildinglocation')),
                ('reports', models.ManyToManyField(related_name='maintenance_cases', through='maintenance.CaseReport', to='maintenance.issuereport')),
            ],
        ),
        migrations.AddField(
            model_name='casereport',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_reports', to='maintenance.maintenancecase'),
        ),
        migrations.CreateModel(
            name='TriageDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=128)),
                ('urgency', models.CharField(max_length=16)),
                ('department', models.CharField(max_length=128)),
                ('deadline_minutes', models.PositiveIntegerField()),
                ('differences', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.buildinglocation')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='triage_decision', to='maintenance.issuereport')),
                ('suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maintenance.triagesuggestion')),
            ],
        ),
        migrations.AddField(
            model_name='maintenancecase',
            name='decision',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='case', to='maintenance.triagedecision'),
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=16)),
                ('deadline_at', models.DateTimeField()),
                ('requires_spending', models.BooleanField()),
                ('authorization_status', models.CharField(choices=[('NOT_REQUIRED', 'Not required'), ('PENDING', 'Pending'), ('AUTHORIZED', 'Authorized')], default='NOT_REQUIRED', max_length=16)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In progress'), ('AWAITING_ACCEPTANCE', 'Awaiting acceptance'), ('ACCEPTED', 'Accepted'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='ASSIGNED', max_length=24)),
                ('emergency', models.BooleanField(default=False)),
                ('drill', models.BooleanField(default=False)),
                ('cause', models.TextField(blank=True)),
                ('result', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='maintenance.maintenancecase')),
            ],
        ),
        migrations.CreateModel(
            name='WorkUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.TextField()),
                ('result', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updates', to='maintenance.workorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkUpdateEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('BEFORE', 'Before'), ('AFTER', 'After')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_links', to='maintenance.workupdate')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.documentversion')),
            ],
        ),
        migrations.AddField(
            model_name='workupdate',
            name='evidence',
            field=models.ManyToManyField(related_name='work_updates', through='maintenance.WorkUpdateEvidence', to='documents.documentversion'),
        ),
        migrations.AddConstraint(
            model_name='casereport',
            constraint=models.UniqueConstraint(fields=('case', 'report'), name='case_report_once'),
        ),
        migrations.AddConstraint(
            model_name='workupdateevidence',
            constraint=models.UniqueConstraint(fields=('update', 'version'), name='work_update_evidence_once'),
        ),
        migrations.RunSQL(
            """
            CREATE FUNCTION maintenance_reject_append_only()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'work updates and evidence are append-only'
                USING ERRCODE = 'check_violation';
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER work_update_append_only
            BEFORE UPDATE OR DELETE ON maintenance_workupdate
            FOR EACH ROW EXECUTE FUNCTION maintenance_reject_append_only();

            CREATE TRIGGER work_update_evidence_append_only
            BEFORE UPDATE OR DELETE ON maintenance_workupdateevidence
            FOR EACH ROW EXECUTE FUNCTION maintenance_reject_append_only();

            CREATE FUNCTION maintenance_reject_paid_diagnostic()
            RETURNS trigger AS $$
            BEGIN
                IF NOT OLD.requires_spending AND NEW.requires_spending THEN
                    RAISE EXCEPTION 'diagnostic work orders cannot become paid work orders'
                    USING ERRCODE = 'check_violation';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER work_order_cannot_become_paid
            BEFORE UPDATE OF requires_spending ON maintenance_workorder
            FOR EACH ROW EXECUTE FUNCTION maintenance_reject_paid_diagnostic();
            """,
            """
            DROP TRIGGER work_order_cannot_become_paid ON maintenance_workorder;
            DROP FUNCTION maintenance_reject_paid_diagnostic();
            DROP TRIGGER work_update_evidence_append_only ON maintenance_workupdateevidence;
            DROP TRIGGER work_update_append_only ON maintenance_workupdate;
            DROP FUNCTION maintenance_reject_append_only();
            """,
        ),
    ]
