# Generated by Django 5.2.16 on 2026-07-13 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_emergency_authorized_state_invariant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField()),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completion_ratings', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completion_ratings', to='maintenance.workorder')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('resident', 'work_order'), name='completion_rating_once_per_resident_work_order'), models.CheckConstraint(condition=models.Q(('score__gte', 1), ('score__lte', 5)), name='completion_rating_score_range')],
            },
        ),
    ]
