# Generated by Django 5.2.16 on 2026-07-14 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_unit_unit_id_building_key'),
        ('maintenance', '0009_completion_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='building',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issue_reports', to='accounts.building'),
        ),
        migrations.AddConstraint(
            model_name='buildinglocation',
            constraint=models.UniqueConstraint(fields=('id', 'building'), name='location_id_building_key'),
        ),
    ]
