# Generated by Django 5.2.16 on 2026-07-14 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_unit_unit_id_building_key'),
        ('maintenance', '0011_report_building_backfill_and_composite_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuereport',
            name='building',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='issue_reports', to='accounts.building'),
        ),
    ]
