# Generated by Django 5.2.16 on 2026-07-15 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_unit_unit_id_building_key'),
        ('maintenance', '0012_report_building_not_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='client_ref',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='issuereport',
            constraint=models.UniqueConstraint(condition=models.Q(('client_ref__isnull', False)), fields=('reporter', 'client_ref'), name='report_client_ref_once'),
        ),
    ]
