# Generated by Django 5.2.16 on 2026-07-21 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0014_reportphoto_content_sha'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workorder',
            name='work_order_emergency_request_identity',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='drill',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='emergency',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='emergency_reason',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='emergency_requested_at',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='emergency_requested_by',
        ),
    ]
