# Generated by Django 5.2.16 on 2026-07-21 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0015_remove_workorder_work_order_emergency_request_identity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='declined_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='declined_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='declined_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenancecase',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancecase',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triagesuggestion',
            name='missing_information',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('IN_REVIEW', 'In review'), ('NEEDS_INFO', 'Needs information'), ('DECLINED', 'Declined'), ('IN_PROGRESS', 'In progress'), ('PROPOSED', 'Proposed'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='SUBMITTED', max_length=16),
        ),
        migrations.CreateModel(
            name='InfoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reply_text', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='info_requests', to='maintenance.issuereport')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True)), fields=('report',), name='one_open_info_request_per_report')],
            },
        ),
    ]
