# Generated by Django 5.2.16 on 2026-07-21 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_remove_publishedledgerentry_work_order'),
        ('maintenance', '0016_issuereport_declined_at_issuereport_declined_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='completionrating',
            name='completion_rating_once_per_resident_work_order',
        ),
        migrations.RemoveConstraint(
            model_name='completionrating',
            name='completion_rating_score_range',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='case',
        ),
        migrations.RemoveField(
            model_name='workupdate',
            name='work_order',
        ),
        migrations.RemoveField(
            model_name='completionrating',
            name='work_order',
        ),
        migrations.RemoveField(
            model_name='completionrating',
            name='score',
        ),
        migrations.AddField(
            model_name='completionrating',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completion_ratings', to='maintenance.maintenancecase'),
        ),
        migrations.AddField(
            model_name='completionrating',
            name='satisfied',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='workupdate',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updates', to='maintenance.maintenancecase'),
        ),
        migrations.AddConstraint(
            model_name='completionrating',
            constraint=models.UniqueConstraint(fields=('resident', 'case'), name='completion_rating_once_per_resident_case'),
        ),
        migrations.DeleteModel(
            name='WorkOrder',
        ),
    ]
