# Generated by Django 5.2.16 on 2026-07-21 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0017_remove_workorder_assignee_remove_workorder_case_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completionrating',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completion_ratings', to='maintenance.maintenancecase'),
        ),
        migrations.AlterField(
            model_name='completionrating',
            name='satisfied',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='workupdate',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updates', to='maintenance.maintenancecase'),
        ),
    ]
