# Generated by Django 5.2.16 on 2026-07-21 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_kind'),
        ('finance', '0018_proposal_building_proposal_closed_at_and_more'),
        ('maintenance', '0018_alter_completionrating_case_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='completionrating',
            name='completion_rating_once_per_resident_case',
        ),
        migrations.AddField(
            model_name='completionrating',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completion_ratings', to='finance.proposal'),
        ),
        migrations.AddField(
            model_name='workupdate',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updates', to='finance.proposal'),
        ),
        migrations.AlterField(
            model_name='completionrating',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completion_ratings', to='maintenance.maintenancecase'),
        ),
        migrations.AlterField(
            model_name='workupdate',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updates', to='maintenance.maintenancecase'),
        ),
        migrations.AddConstraint(
            model_name='completionrating',
            constraint=models.UniqueConstraint(condition=models.Q(('case__isnull', False)), fields=('resident', 'case'), name='completion_rating_once_per_resident_case'),
        ),
        migrations.AddConstraint(
            model_name='completionrating',
            constraint=models.UniqueConstraint(condition=models.Q(('proposal__isnull', False)), fields=('resident', 'proposal'), name='completion_rating_once_per_resident_proposal'),
        ),
        migrations.AddConstraint(
            model_name='completionrating',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('case__isnull', False), ('proposal__isnull', True)), models.Q(('case__isnull', True), ('proposal__isnull', False)), _connector='OR'), name='completion_rating_case_xor_proposal'),
        ),
        migrations.AddConstraint(
            model_name='workupdate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('case__isnull', False), ('proposal__isnull', True)), models.Q(('case__isnull', True), ('proposal__isnull', False)), _connector='OR'), name='work_update_case_xor_proposal'),
        ),
    ]
