# Generated by Django 5.2.16 on 2026-07-26 12:02

import re

from django.db import migrations, models

CODES = {
    'ELEVATOR', 'WATER_LEAK', 'ELECTRICAL_FAULT', 'HEATING_COOLING', 'LIGHTING',
    'DOOR_LOCK', 'APPLIANCE', 'STRUCTURAL', 'CLEANLINESS', 'NOISE', 'OTHER',
}


def _to_code(value):
    code = re.sub(r'[^A-Z0-9]+', '_', str(value).upper()).strip('_')
    return code if code in CODES else 'OTHER'


def map_legacy_categories(apps, schema_editor):
    for model_name in ('MaintenanceCase', 'TriageDecision', 'TriageSuggestion'):
        model = apps.get_model('maintenance', model_name)
        for row in model.objects.exclude(category__in=CODES):
            row.category = _to_code(row.category)
            row.save(update_fields=['category'])


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0020_workupdate_author'),
    ]

    operations = [
        migrations.RunPython(map_legacy_categories, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='maintenancecase',
            name='category',
            field=models.CharField(choices=[('ELEVATOR', 'Elevator'), ('WATER_LEAK', 'Water leak'), ('ELECTRICAL_FAULT', 'Electrical fault'), ('HEATING_COOLING', 'Heating / cooling'), ('LIGHTING', 'Lighting'), ('DOOR_LOCK', 'Door / lock'), ('APPLIANCE', 'Appliance'), ('STRUCTURAL', 'Structural'), ('CLEANLINESS', 'Cleanliness'), ('NOISE', 'Noise'), ('OTHER', 'Other')], max_length=128),
        ),
        migrations.AlterField(
            model_name='triagedecision',
            name='category',
            field=models.CharField(choices=[('ELEVATOR', 'Elevator'), ('WATER_LEAK', 'Water leak'), ('ELECTRICAL_FAULT', 'Electrical fault'), ('HEATING_COOLING', 'Heating / cooling'), ('LIGHTING', 'Lighting'), ('DOOR_LOCK', 'Door / lock'), ('APPLIANCE', 'Appliance'), ('STRUCTURAL', 'Structural'), ('CLEANLINESS', 'Cleanliness'), ('NOISE', 'Noise'), ('OTHER', 'Other')], max_length=128),
        ),
        migrations.AlterField(
            model_name='triagesuggestion',
            name='category',
            field=models.CharField(choices=[('ELEVATOR', 'Elevator'), ('WATER_LEAK', 'Water leak'), ('ELECTRICAL_FAULT', 'Electrical fault'), ('HEATING_COOLING', 'Heating / cooling'), ('LIGHTING', 'Lighting'), ('DOOR_LOCK', 'Door / lock'), ('APPLIANCE', 'Appliance'), ('STRUCTURAL', 'Structural'), ('CLEANLINESS', 'Cleanliness'), ('NOISE', 'Noise'), ('OTHER', 'Other')], max_length=128),
        ),
    ]
