# Generated by Django 5.2.16 on 2026-08-14 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0021_alter_maintenancecase_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workupdate',
            name='evidence',
        ),
        migrations.DeleteModel(
            name='WorkUpdateEvidence',
        ),
    ]
