# Generated by Django 5.2.16 on 2026-07-24 08:29

import django.db.models.deletion
import lamto.billing.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0018_registrationrequest'),
        ('documents', '0005_remove_documentversion_redacts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('note', models.TextField(blank=True, max_length=500)),
                ('period', models.CharField(blank=True, max_length=64)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount_vnd', models.PositiveBigIntegerField()),
                ('reference', models.CharField(default=lamto.billing.models.new_reference, editable=False, max_length=64)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('PAID', 'Paid'), ('VOID', 'Void')], default='ISSUED', max_length=16)),
                ('payment_source', models.CharField(blank=True, choices=[('SELF_ATTESTED_DEMO', 'Resident self-attested (demo)'), ('BANK_WEBHOOK', 'Bank webhook'), ('MANAGEMENT_MANUAL', 'Management manual')], max_length=32)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('void_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='accounts.building')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='documents.documentversion')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_bills', to=settings.AUTH_USER_MODEL)),
                ('paid_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_bills', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to=settings.AUTH_USER_MODEL)),
                ('void_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_vnd__gt', 0)), name='bill_amount_positive')],
            },
        ),
    ]
