#!/usr/bin/env bash
# Generate a four-validator QBFT development network for LamTo evidence anchoring.
#
# Validator roles (deterministic order of generated keys):
#   Node-1  Management Board
#   Node-2  property-management operator
#   Node-3  resident representative
#   Node-4  auditor
#
# Never commit generated keys, .env.network, or Node-* data directories.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

BESU_IMAGE="${BESU_IMAGE:-hyperledger/besu:25.7.0}"
CONFIG_FILE="${CONFIG_FILE:-qbftConfigFile.json}"
NETWORK_FILES="${NETWORK_FILES:-networkFiles}"

NODE_LABELS=(
  "Management Board"
  "property-management operator"
  "resident representative"
  "auditor"
)

echo "==> Generating QBFT blockchain config with ${BESU_IMAGE}"
rm -rf "${NETWORK_FILES}"
docker run --rm \
  -v "${ROOT}:/opt/besu" \
  -w /opt/besu \
  "${BESU_IMAGE}" \
  operator generate-blockchain-config \
  --config-file="${CONFIG_FILE}" \
  --to="${NETWORK_FILES}" \
  --private-key-file-name=key

if [[ ! -f "${NETWORK_FILES}/genesis.json" ]]; then
  echo "error: genesis.json was not generated under ${NETWORK_FILES}" >&2
  exit 1
fi

# Collect validator key directories in stable lexical order (addresses are hex).
mapfile -t KEY_DIRS < <(find "${NETWORK_FILES}/keys" -mindepth 1 -maxdepth 1 -type d | sort)
if [[ "${#KEY_DIRS[@]}" -ne 4 ]]; then
  echo "error: expected 4 validator key directories, found ${#KEY_DIRS[@]}" >&2
  exit 1
fi

for index in 0 1 2 3; do
  node_num=$((index + 1))
  node_dir="Node-${node_num}"
  src="${KEY_DIRS[$index]}"
  address="$(basename "${src}")"
  label="${NODE_LABELS[$index]}"

  echo "==> Node-${node_num} (${label}) address=${address}"
  rm -rf "${node_dir}"
  mkdir -p "${node_dir}/data"
  cp "${NETWORK_FILES}/genesis.json" "${node_dir}/genesis.json"
  cp "${src}/key" "${node_dir}/data/key"
  if [[ -f "${src}/key.pub" ]]; then
    cp "${src}/key.pub" "${node_dir}/data/key.pub"
  fi
  # Role label for operators (not read by Besu).
  printf '%s\n' "${label}" > "${node_dir}/ROLE.txt"
  printf '%s\n' "${address}" > "${node_dir}/ADDRESS.txt"
done

# Derive Node-1 enode for peer bootstrapping.
NODE1_KEY_HEX="$(tr -d '[:space:]' < Node-1/data/key | sed 's/^0x//')"
NODE1_PUB="$(
  docker run --rm -i --entrypoint /bin/sh "${BESU_IMAGE}" -c \
    'command -v node >/dev/null 2>&1 && node -e "
      const {privateToPublic, toBuffer} = require(\"ethereumjs-util\");
      const key = Buffer.from(process.argv[1], \"hex\");
      process.stdout.write(privateToPublic(key).toString(\"hex\"));
    " "'"${NODE1_KEY_HEX}"'"' 2>/dev/null || true
)"

if [[ -z "${NODE1_PUB}" ]]; then
  # Fallback: use openssl + Python if available on host for uncompressed pubkey (no 04 prefix).
  if command -v python3 >/dev/null 2>&1; then
    NODE1_PUB="$(
      NODE1_KEY_HEX="${NODE1_KEY_HEX}" python3 - <<'PY'
import os
from eth_keys import keys
key_hex = os.environ["NODE1_KEY_HEX"]
pk = keys.PrivateKey(bytes.fromhex(key_hex))
print(pk.public_key.to_hex()[2:])  # strip 0x; eth_keys may include 04
pub = pk.public_key.to_bytes()
if len(pub) == 65 and pub[0] == 4:
    pub = pub[1:]
print(pub.hex())
PY
    )"
    # python snippet prints twice if both paths run; take last non-empty line
    NODE1_PUB="$(printf '%s\n' "${NODE1_PUB}" | awk 'NF{p=$0} END{print p}')"
  fi
fi

if [[ -z "${NODE1_PUB}" ]]; then
  echo "warning: could not derive Node-1 public key; writing placeholder enode" >&2
  NODE1_PUB="UNKNOWN"
fi

# Compose attaches Node-1 hostname as node1 on the besu network.
ENODE="enode://${NODE1_PUB}@node1:30303"
cat > .env.network <<EOF
# Generated by generate-network.sh — do not commit
NODE1_ENODE=${ENODE}
NODE1_ROLE=Management Board
NODE2_ROLE=property-management operator
NODE3_ROLE=resident representative
NODE4_ROLE=auditor
EOF

echo "==> Wrote .env.network with Node-1 enode"
echo "==> Network generation complete."
echo "    Start with: docker compose up -d"
echo "    RPC:        http://127.0.0.1:8545 (Node-1 only)"
