#!/usr/bin/env bash
# Generate a four-validator QBFT development network for LamTo evidence anchoring.
#
# Validator roles (deterministic order of generated keys):
#   Node-1  Management Board
#   Node-2  property-management operator
#   Node-3  resident representative
#   Node-4  auditor
#
# Never commit generated keys, .env.network, or Node-* data directories.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

BESU_IMAGE="${BESU_IMAGE:-hyperledger/besu:25.7.0}"
CONFIG_FILE="${CONFIG_FILE:-qbftConfigFile.json}"
NETWORK_FILES="${NETWORK_FILES:-networkFiles}"
PROJECT_ROOT="$(cd "${ROOT}/../.." && pwd)"

NODE_LABELS=(
  "Management Board"
  "property-management operator"
  "resident representative"
  "auditor"
)

echo "==> Generating QBFT blockchain config with ${BESU_IMAGE}"
rm -rf "${NETWORK_FILES}"
docker run --rm \
  -v "${ROOT}:/opt/besu" \
  -w /opt/besu \
  "${BESU_IMAGE}" \
  operator generate-blockchain-config \
  --config-file="${CONFIG_FILE}" \
  --to="${NETWORK_FILES}" \
  --private-key-file-name=key

if [[ ! -f "${NETWORK_FILES}/genesis.json" ]]; then
  echo "error: genesis.json was not generated under ${NETWORK_FILES}" >&2
  exit 1
fi

# Collect validator key directories in stable lexical order (addresses are hex).
mapfile -t KEY_DIRS < <(find "${NETWORK_FILES}/keys" -mindepth 1 -maxdepth 1 -type d | sort)
if [[ "${#KEY_DIRS[@]}" -ne 4 ]]; then
  echo "error: expected 4 validator key directories, found ${#KEY_DIRS[@]}" >&2
  exit 1
fi

for index in 0 1 2 3; do
  node_num=$((index + 1))
  node_dir="Node-${node_num}"
  src="${KEY_DIRS[$index]}"
  address="$(basename "${src}")"
  label="${NODE_LABELS[$index]}"

  echo "==> Node-${node_num} (${label}) address=${address}"
  rm -rf "${node_dir}"
  mkdir -p "${node_dir}/data"
  cp "${NETWORK_FILES}/genesis.json" "${node_dir}/genesis.json"
  cp "${src}/key" "${node_dir}/data/key"
  if [[ -f "${src}/key.pub" ]]; then
    cp "${src}/key.pub" "${node_dir}/data/key.pub"
  fi
  # Role label for operators (not read by Besu).
  printf '%s\n' "${label}" > "${node_dir}/ROLE.txt"
  printf '%s\n' "${address}" > "${node_dir}/ADDRESS.txt"
done

# Derive Node-1 enode for peer bootstrapping (fail hard if pubkey cannot be derived).
# Host must be the Compose service name so other validators resolve via Docker DNS.
NODE1_KEY_HEX="$(tr -d '[:space:]' < Node-1/data/key | sed 's/^0x//')"
NODE1_PUB=""

derive_pub_python() {
  local py="$1"
  NODE1_KEY_HEX="${NODE1_KEY_HEX}" "${py}" - <<'PY'
import os
import sys

key_hex = os.environ["NODE1_KEY_HEX"]
try:
    from eth_keys import keys
except ImportError:
    try:
        # eth_account typically depends on eth_keys; try import surface first.
        import eth_account  # noqa: F401
        from eth_keys import keys
    except ImportError as exc:
        sys.stderr.write(f"eth_keys/eth_account unavailable: {exc}\n")
        sys.exit(2)

pk = keys.PrivateKey(bytes.fromhex(key_hex))
pub = pk.public_key.to_bytes()
if len(pub) == 65 and pub[0] == 4:
    pub = pub[1:]
sys.stdout.write(pub.hex())
PY
}

# Prefer project venv (has eth_keys/eth_account), then cast, then bare python3, then Besu image node.
if [[ -x "${PROJECT_ROOT}/.venv/bin/python" ]]; then
  NODE1_PUB="$(derive_pub_python "${PROJECT_ROOT}/.venv/bin/python" 2>/dev/null || true)"
fi

if [[ -z "${NODE1_PUB}" ]] && command -v cast >/dev/null 2>&1; then
  NODE1_PUB="$(
    cast wallet public-key --private-key "0x${NODE1_KEY_HEX}" 2>/dev/null \
      | tr -d '[:space:]' | sed 's/^0x//' | sed 's/^04//'
  )"
fi

if [[ -z "${NODE1_PUB}" ]] && command -v python3 >/dev/null 2>&1; then
  NODE1_PUB="$(derive_pub_python python3 2>/dev/null || true)"
fi

if [[ -z "${NODE1_PUB}" ]]; then
  NODE1_PUB="$(
    docker run --rm -i --entrypoint /bin/sh "${BESU_IMAGE}" -c \
      'command -v node >/dev/null 2>&1 && node -e "
        const {privateToPublic} = require(\"ethereumjs-util\");
        const key = Buffer.from(process.argv[1], \"hex\");
        process.stdout.write(privateToPublic(key).toString(\"hex\"));
      " "'"${NODE1_KEY_HEX}"'"' 2>/dev/null || true
  )"
fi

# Uncompressed secp256k1 public key without 0x/04 prefix: 64 bytes → 128 hex chars.
if [[ ! "${NODE1_PUB}" =~ ^[0-9a-fA-F]{128}$ ]]; then
  echo "error: could not derive Node-1 public key for enode (got '${NODE1_PUB:-empty}')" >&2
  echo "hint: install eth_keys in project .venv, or install foundry cast" >&2
  exit 1
fi

ENODE="enode://${NODE1_PUB}@validator1:30303"
cat > .env.network <<EOF
# Generated by generate-network.sh — do not commit
NODE1_ENODE=${ENODE}
NODE1_ROLE=Management Board
NODE2_ROLE=property-management operator
NODE3_ROLE=resident representative
NODE4_ROLE=auditor
EOF

echo "==> Wrote .env.network with Node-1 enode @validator1:30303"
echo "==> Network generation complete."
echo "    Start with: docker compose up -d"
echo "    RPC:        http://127.0.0.1:8545 (Node-1 / validator1 only)"
echo "    Peer check: curl -s -X POST http://127.0.0.1:8545 -H 'Content-Type: application/json' \\"
echo "                -d '{\"jsonrpc\":\"2.0\",\"method\":\"net_peerCount\",\"params\":[],\"id\":1}'"
echo "                # expect result \"0x3\" once all four validators have peered"
