# Generated by Django 5.2.16 on 2026-07-13 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_signer_wallets'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainOutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=66, unique=True)),
                ('event_type', models.PositiveSmallIntegerField(choices=[(1, 'Proposal created'), (2, 'Board approval'), (3, 'Representative approval'), (4, 'Emergency authorization'), (5, 'Emergency outcome'), (6, 'Work acceptance'), (7, 'Payment recorded'), (8, 'Payment verified'), (9, 'Publication snapshot'), (10, 'Correction'), (11, 'Fund entry')])),
                ('payload', models.JSONField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('previous_hash', models.CharField(max_length=66)),
                ('signature', models.CharField(max_length=132)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('MISMATCH', 'Mismatch')], default='PENDING', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=66)),
                ('receipt_status', models.IntegerField(blank=True, null=True)),
                ('receipt', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('chain_confirmed_block', models.BigIntegerField(blank=True, null=True)),
                ('chain_block_timestamp', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signer_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.signerwallet')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('event_id__regex', '^0x[0-9a-f]{64}$')), name='outbox_event_id_bytes32'), models.CheckConstraint(condition=models.Q(('payload_hash__regex', '^[0-9a-f]{64}$')), name='outbox_payload_hash_sha256'), models.CheckConstraint(condition=models.Q(('previous_hash__regex', '^0x[0-9a-f]{64}$')), name='outbox_previous_hash_bytes32'), models.CheckConstraint(condition=models.Q(('event_type__gte', 1), ('event_type__lte', 11)), name='outbox_known_event_type')],
            },
        ),
        migrations.RunSQL(
            """
            CREATE FUNCTION evidence_protect_outbox_identity()
            RETURNS trigger AS $$
            BEGIN
                IF TG_OP = 'DELETE' OR OLD.event_id IS DISTINCT FROM NEW.event_id
                   OR OLD.event_type IS DISTINCT FROM NEW.event_type
                   OR OLD.payload IS DISTINCT FROM NEW.payload
                   OR OLD.payload_hash IS DISTINCT FROM NEW.payload_hash
                   OR OLD.previous_hash IS DISTINCT FROM NEW.previous_hash
                   OR OLD.signer_wallet_id IS DISTINCT FROM NEW.signer_wallet_id
                   OR OLD.signature IS DISTINCT FROM NEW.signature
                   OR OLD.created_at IS DISTINCT FROM NEW.created_at THEN
                    RAISE EXCEPTION 'signed outbox identity is immutable' USING ERRCODE = 'check_violation';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER blockchain_outbox_identity
            BEFORE UPDATE OR DELETE ON evidence_blockchainoutboxevent
            FOR EACH ROW EXECUTE FUNCTION evidence_protect_outbox_identity();
            """,
            """
            DROP TRIGGER blockchain_outbox_identity ON evidence_blockchainoutboxevent;
            DROP FUNCTION evidence_protect_outbox_identity();
            """,
        ),
    ]
