# Generated by Django 5.2.16 on 2026-07-14 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_phone'),
        ('evidence', '0007_revoke_legacy_runtime_execute'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainoutboxevent',
            name='building',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outbox_events', to='accounts.building'),
        ),
    ]
