# Generated by Django 5.2.16 on 2026-07-14 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_phone'),
        ('evidence', '0009_outbox_building_backfill_and_guard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchainoutboxevent',
            name='building',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='outbox_events', to='accounts.building'),
        ),
    ]
