# Generated by Django 5.2.16 on 2026-07-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0010_outbox_building_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchainoutboxevent',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('LOCAL', 'Locally settled'), ('FAILED', 'Failed'), ('MISMATCH', 'Mismatch')], default='PENDING', max_length=16),
        ),
    ]
