# Generated by Django 5.2.16 on 2026-07-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0011_outbox_local_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchainoutboxevent',
            name='event_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Proposal created'), (2, 'Board approval'), (3, 'Representative approval'), (4, 'Emergency authorization'), (5, 'Emergency outcome'), (6, 'Work acceptance'), (7, 'Payment recorded'), (8, 'Payment verified'), (9, 'Publication snapshot'), (10, 'Reserved'), (11, 'Fund entry')]),
        ),
    ]
