# Generated by Django 5.2.16 on 2026-07-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0012_alter_blockchainoutboxevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchainoutboxevent',
            name='event_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Proposal created'), (2, 'Board approval'), (3, 'Representative approval'), (4, 'Reserved'), (5, 'Reserved'), (6, 'Work acceptance'), (7, 'Payment recorded'), (8, 'Payment verified'), (9, 'Publication snapshot'), (10, 'Reserved'), (11, 'Fund entry')]),
        ),
    ]
