# Generated by Django 5.2.16 on 2026-07-21 18:18

import os
from importlib import import_module

import django.db.models.deletion
from django.db import migrations, models


PLATFORM_OUTBOX_FUNCTION = r"""
CREATE FUNCTION lamto_security.evidence_insert_platform_outbox_event(
    p_event_id text, p_event_type smallint, p_payload jsonb, p_payload_hash text,
    p_previous_hash text, p_signature text, p_signer_address text, p_building_id bigint,
    p_canonical_payload text, p_authorization text
) RETURNS bigint
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
DECLARE event_pk bigint;
BEGIN
    IF p_payload IS DISTINCT FROM p_canonical_payload::jsonb THEN
        RAISE EXCEPTION 'canonical evidence payload does not match the queued payload'
        USING ERRCODE = 'check_violation';
    END IF;
    IF p_authorization IS DISTINCT FROM (
        SELECT encode(
            sha256(secret || sha256(secret || convert_to(format(
                'platform-evidence-queue|%s|%s|%s|%s|%s|%s|%s|%s',
                p_event_id, p_event_type, p_payload_hash, p_previous_hash,
                p_signature, p_signer_address, p_building_id, p_canonical_payload
            ), 'UTF8'))), 'hex'
        )
        FROM lamto_security.write_authorization_secret WHERE id = TRUE
    ) THEN
        RAISE EXCEPTION 'platform evidence queue authorization is invalid'
        USING ERRCODE = 'insufficient_privilege';
    END IF;
    PERFORM 1 FROM public.accounts_building WHERE id = p_building_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'building does not exist' USING ERRCODE = 'foreign_key_violation';
    END IF;
    INSERT INTO public.evidence_blockchainoutboxevent
        (event_id, event_type, payload, payload_hash, previous_hash, signature,
         signer_wallet_id, signer_address, building_id, status, attempts, receipt,
         transaction_hash, last_error, created_at, updated_at)
    VALUES
        (p_event_id, p_event_type, p_payload, p_payload_hash, p_previous_hash,
         p_signature, NULL, p_signer_address, p_building_id, 'PENDING', 0, '{}'::jsonb,
         '', '', clock_timestamp(), clock_timestamp())
    RETURNING id INTO event_pk;
    RETURN event_pk;
END;
$$;
REVOKE ALL ON FUNCTION lamto_security.evidence_insert_platform_outbox_event(
    text, smallint, jsonb, text, text, text, text, bigint, text, text
) FROM PUBLIC;
"""


def create_platform_outbox_function(apps, schema_editor):
    service_role = os.getenv("POSTGRES_SERVICE_ROLE") or "lamto_service"
    executor_role = os.getenv("POSTGRES_EXECUTOR_ROLE") or "lamto_writer"
    quote = schema_editor.connection.ops.quote_name
    signature = (
        "lamto_security.evidence_insert_platform_outbox_event("
        "text,smallint,jsonb,text,text,text,text,bigint,text,text)"
    )
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT current_user")
        current_role = cursor.fetchone()[0]
        cursor.execute("GRANT SELECT ON TABLE accounts_building TO " + quote(service_role))
        cursor.execute("SET ROLE " + quote(service_role))
        try:
            cursor.execute(PLATFORM_OUTBOX_FUNCTION)
            cursor.execute("GRANT EXECUTE ON FUNCTION " + signature + " TO " + quote(executor_role))
            cursor.execute("GRANT EXECUTE ON FUNCTION " + signature + " TO " + quote(current_role))
        finally:
            cursor.execute("RESET ROLE")


def update_wallet_outbox_function_and_guard(apps, schema_editor):
    legacy = import_module(
        "lamto.evidence.migrations.0015_management_outbox_procedure"
    ).MANAGEMENT_OUTBOX_PROCEDURE
    legacy = legacy.replace(
        "signer_wallet_id, building_id, status",
        "signer_wallet_id, signer_address, building_id, status",
    ).replace(
        "p_signature, p_wallet_id, v_building_id, 'PENDING'",
        "p_signature, p_wallet_id, '', v_building_id, 'PENDING'",
    )
    guard = import_module(
        "lamto.evidence.migrations.0009_outbox_building_backfill_and_guard"
    ).IDENTITY_TRIGGER_WITH_BUILDING.replace(
        "       OR OLD.signer_wallet_id IS DISTINCT FROM NEW.signer_wallet_id\n",
        "       OR OLD.signer_wallet_id IS DISTINCT FROM NEW.signer_wallet_id\n"
        "       OR OLD.signer_address IS DISTINCT FROM NEW.signer_address\n",
    )
    service_role = schema_editor.connection.ops.quote_name(
        os.getenv("POSTGRES_SERVICE_ROLE") or "lamto_service"
    )
    schema_editor.execute(
        legacy.replace("__SERVICE_ROLE__", service_role).replace("%", "%%")
    )
    schema_editor.execute(guard)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_breakglasssession_authorizing_membership_and_more'),
        ('evidence', '0015_management_outbox_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainoutboxevent',
            name='signer_address',
            field=models.CharField(blank=True, default='', max_length=42),
        ),
        migrations.AlterField(
            model_name='blockchainoutboxevent',
            name='signer_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.signerwallet'),
        ),
        migrations.RunPython(update_wallet_outbox_function_and_guard, migrations.RunPython.noop),
        migrations.RunPython(create_platform_outbox_function, migrations.RunPython.noop),
    ]
