# Generated by Django 5.2.16 on 2026-07-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0016_blockchainoutboxevent_signer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchainoutboxevent',
            name='event_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Proposal created'), (2, 'Reserved'), (3, 'Reserved'), (4, 'Reserved'), (5, 'Reserved'), (6, 'Reserved'), (7, 'Payment recorded'), (8, 'Payment verified'), (9, 'Publication snapshot'), (10, 'Settlement'), (11, 'Fund entry')]),
        ),
    ]
