# Generated by Django 5.2.16 on 2026-07-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0018_two_anchored_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockchainoutboxevent',
            name='signer_wallet',
        ),
        migrations.AlterField(
            model_name='blockchainoutboxevent',
            name='signer_address',
            field=models.CharField(max_length=42),
        ),
    ]
