# Generated by Django 5.2.16 on 2026-07-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_signerwallet_membership_and_more'),
        ('evidence', '0020_drop_signed_write_procedures'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='blockchainoutboxevent',
            constraint=models.CheckConstraint(condition=models.Q(('signer_address', ''), _negated=True), name='outbox_signer_address_required'),
        ),
    ]
