# Generated by Django 5.2.16 on 2026-07-12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0002_capability_grants"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("action", models.CharField(max_length=128)),
                ("target_type", models.CharField(max_length=128)),
                ("target_id", models.CharField(max_length=255)),
                ("metadata", models.JSONField(default=dict)),
                ("result", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.organizationmembership",
                    ),
                ),
            ],
        ),
        migrations.RunSQL(
            """
            CREATE FUNCTION audit_prevent_mutation()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'audit events are append-only'
                USING ERRCODE = 'check_violation';
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER audit_event_append_only
            BEFORE UPDATE OR DELETE ON audit_auditevent
            FOR EACH ROW EXECUTE FUNCTION audit_prevent_mutation();
            """,
            """
            DROP TRIGGER audit_event_append_only ON audit_auditevent;
            DROP FUNCTION audit_prevent_mutation();
            """,
        ),
    ]
