# Generated by Django 5.2.16 on 2026-07-21 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_managementmembership'),
        ('audit', '0002_alter_auditevent_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.managementmembership'),
        ),
    ]
