# Generated by Django 5.2.16 on 2026-07-22 14:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0016_remove_signerwallet_membership_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GatePurgeHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_success_at', models.DateTimeField()),
                ('events_deleted', models.PositiveIntegerField(default=0)),
                ('photos_deleted', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FaceEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.BinaryField(blank=True, help_text='Fernet-sealed float32 vector; NULL once deleted.', null=True)),
                ('model_name', models.CharField(blank=True, max_length=64)),
                ('model_version', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired before review')], default='PENDING', max_length=16)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=255)),
                ('occupancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_enrollment', to='accounts.residentoccupancy')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GateDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('direction', models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit')], max_length=8)),
                ('active', models.BooleanField(default=True)),
                ('last_seen_hour', models.DateTimeField(blank=True, help_text='Truncated to the hour on purpose: enough to see a reader go dark, too coarse to place anyone at the gate.', null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_devices', to='accounts.building')),
            ],
        ),
        migrations.CreateModel(
            name='GateDeviceCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_sha256', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='gate.gatedevice')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PendingEnrollmentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(max_length=512, unique=True)),
                ('provider_version_id', models.CharField(blank=True, max_length=512)),
                ('content_type', models.CharField(max_length=127)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_photo', to='gate.faceenrollment')),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(help_text='Normalized form only.', max_length=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired before review')], default='PENDING', max_length=16)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=255)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_plates', to='accounts.building')),
                ('occupancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_plates', to='accounts.residentoccupancy')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('FACE', 'Face'), ('PLATE', 'Plate')], max_length=8)),
                ('direction', models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit')], max_length=8)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('raw_plate_text', models.CharField(blank=True, max_length=64)),
                ('normalized_plate_text', models.CharField(blank=True, max_length=12)),
                ('model_name', models.CharField(blank=True, max_length=64)),
                ('model_version', models.CharField(blank=True, max_length=64)),
                ('match_metric', models.CharField(blank=True, max_length=16)),
                ('threshold_used', models.FloatField(blank=True, null=True)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_events', to='accounts.building')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='gate.gatedevice')),
                ('matched_occupancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gate_events', to='accounts.residentoccupancy')),
                ('matched_plate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gate_events', to='gate.vehicleplate')),
            ],
        ),
        migrations.AddConstraint(
            model_name='faceenrollment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['REJECTED', 'EXPIRED']), _negated=True), ('embedding__isnull', True), _connector='OR'), name='gate_no_embedding_when_not_live'),
        ),
        migrations.AddConstraint(
            model_name='vehicleplate',
            constraint=models.UniqueConstraint(fields=('occupancy', 'plate'), name='gate_plate_once_per_occupancy'),
        ),
        migrations.AddConstraint(
            model_name='vehicleplate',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'APPROVED')), fields=('building', 'plate'), name='gate_approved_plate_once_per_building'),
        ),
        migrations.RunSQL(
            """
            CREATE FUNCTION gate_event_prevent_update()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'gate events are append-only'
                USING ERRCODE = 'check_violation';
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER gate_event_append_only
            BEFORE UPDATE ON gate_gateevent
            FOR EACH ROW EXECUTE FUNCTION gate_event_prevent_update();
            """,
            """
            DROP TRIGGER gate_event_append_only ON gate_gateevent;
            DROP FUNCTION gate_event_prevent_update();
            """,
        ),
    ]
