# Generated by Django 5.2.16 on 2026-07-12 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_capability_grants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('REPORT_PHOTO', 'Report photo'), ('BEFORE_PHOTO', 'Before photo'), ('AFTER_PHOTO', 'After photo'), ('QUOTATION', 'Quotation'), ('INVOICE', 'Invoice'), ('ACCEPTANCE_REPORT', 'Acceptance report'), ('PAYMENT_PROOF', 'Payment proof'), ('CONTRACT', 'Contract'), ('CORRECTION_EVIDENCE', 'Correction evidence')], max_length=32)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.building')),
            ],
        ),
        migrations.CreateModel(
            name='QuarantinedUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=127)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('reason', models.CharField(max_length=255)),
                ('storage_key', models.CharField(blank=True, max_length=512, null=True, unique=True)),
                ('provider_version_id', models.CharField(blank=True, max_length=512)),
                ('retention_expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('variant', models.CharField(choices=[('ORIGINAL', 'Original'), ('REDACTED', 'Redacted')], max_length=16)),
                ('storage_key', models.CharField(max_length=512, unique=True)),
                ('provider_version_id', models.CharField(max_length=512)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=127)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('scan_status', models.CharField(choices=[('CLEAN', 'Clean')], default='CLEAN', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='documents.document')),
                ('redacts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redacted_versions', to='documents.documentversion')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('document', 'version'), name='document_version_once')],
            },
        ),
        migrations.RunSQL(
            """
            CREATE FUNCTION document_prevent_mutation()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'document records are append-only'
                USING ERRCODE = 'check_violation';
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER document_version_append_only
            BEFORE UPDATE OR DELETE ON documents_documentversion
            FOR EACH ROW EXECUTE FUNCTION document_prevent_mutation();

            CREATE TRIGGER document_append_only
            BEFORE UPDATE OR DELETE ON documents_document
            FOR EACH ROW EXECUTE FUNCTION document_prevent_mutation();

            CREATE TRIGGER quarantined_upload_append_only
            BEFORE UPDATE OR DELETE ON documents_quarantinedupload
            FOR EACH ROW EXECUTE FUNCTION document_prevent_mutation();

            CREATE TRIGGER document_version_truncate_append_only
            BEFORE TRUNCATE ON documents_documentversion
            FOR EACH STATEMENT EXECUTE FUNCTION document_prevent_mutation();

            CREATE TRIGGER document_truncate_append_only
            BEFORE TRUNCATE ON documents_document
            FOR EACH STATEMENT EXECUTE FUNCTION document_prevent_mutation();

            CREATE TRIGGER quarantined_upload_truncate_append_only
            BEFORE TRUNCATE ON documents_quarantinedupload
            FOR EACH STATEMENT EXECUTE FUNCTION document_prevent_mutation();
            """,
            """
            DROP TRIGGER quarantined_upload_truncate_append_only ON documents_quarantinedupload;
            DROP TRIGGER document_version_truncate_append_only ON documents_documentversion;
            DROP TRIGGER document_truncate_append_only ON documents_document;
            DROP TRIGGER quarantined_upload_append_only ON documents_quarantinedupload;
            DROP TRIGGER document_version_append_only ON documents_documentversion;
            DROP TRIGGER document_append_only ON documents_document;
            DROP FUNCTION document_prevent_mutation();
            """,
        ),
    ]
