# Generated by Django 5.2.16 on 2026-07-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='kind',
            field=models.CharField(choices=[('REPORT_PHOTO', 'Report photo'), ('BEFORE_PHOTO', 'Before photo'), ('AFTER_PHOTO', 'After photo'), ('QUOTATION', 'Quotation'), ('INVOICE', 'Invoice'), ('ACCEPTANCE_REPORT', 'Completion report'), ('PAYMENT_PROOF', 'Payment proof'), ('CONTRACT', 'Contract')], max_length=32),
        ),
    ]
