# Generated by Django 5.2.16 on 2026-07-22 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentversion',
            name='redacts',
        ),
        migrations.RemoveField(
            model_name='documentversion',
            name='variant',
        ),
    ]
