# Generated by Django 5.2.16 on 2026-07-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_documentversion_redacts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='kind',
            field=models.CharField(choices=[('REPORT_PHOTO', 'Report photo'), ('BEFORE_PHOTO', 'Before photo'), ('AFTER_PHOTO', 'After photo'), ('QUOTATION', 'Quotation'), ('INVOICE', 'Invoice'), ('ACCEPTANCE_REPORT', 'Completion report'), ('PAYMENT_PROOF', 'Payment proof'), ('CONTRACT', 'Contract'), ('RESIDENT_BILL', 'Resident bill')], max_length=32),
        ),
    ]
