# Generated by Django 5.2.16 on 2026-08-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='kind',
            field=models.CharField(choices=[('REPORT_PHOTO', 'Report photo'), ('QUOTATION', 'Quotation'), ('INVOICE', 'Invoice'), ('ACCEPTANCE_REPORT', 'Completion report'), ('PAYMENT_PROOF', 'Payment proof'), ('CONTRACT', 'Contract'), ('RESIDENT_BILL', 'Resident bill')], max_length=32),
        ),
    ]
