# Generated by Django 5.2.16 on 2026-07-13 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_grant_signed_executor'),
        ('documents', '0001_initial'),
        ('evidence', '0007_revoke_legacy_runtime_execute'),
        ('maintenance', '0005_case_report_ownership_and_work_order_authorization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('NORMAL', 'Normal'), ('EMERGENCY', 'Emergency')], max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In review'), ('NORMAL_AUTHORIZED', 'Normal authorized'), ('EMERGENCY_EVIDENCE', 'Emergency evidence'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organizationmembership')),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='proposal', to='maintenance.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.documentversion')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('amount_vnd', models.BigIntegerField()),
                ('contractor_name', models.CharField(max_length=255)),
                ('fund_code', models.CharField(default='MAINTENANCE', max_length=32)),
                ('purpose', models.TextField()),
                ('snapshot', models.JSONField()),
                ('snapshot_hash', models.CharField(max_length=64)),
                ('creator_signature', models.CharField(max_length=132)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organizationmembership')),
                ('creator_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.signerwallet')),
                ('outbox_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='proposal_version', to='evidence.blockchainoutboxevent')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='finance.proposal')),
                ('quotations', models.ManyToManyField(related_name='proposal_versions', through='finance.ProposalDocument', to='documents.documentversion')),
            ],
        ),
        migrations.AddField(
            model_name='proposaldocument',
            name='proposal_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.proposalversion'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.proposalversion'),
        ),
        migrations.AddConstraint(
            model_name='proposalversion',
            constraint=models.UniqueConstraint(fields=('proposal', 'number'), name='proposal_version_once'),
        ),
        migrations.AddConstraint(
            model_name='proposalversion',
            constraint=models.CheckConstraint(condition=models.Q(('amount_vnd__gt', 0)), name='proposal_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='proposaldocument',
            constraint=models.UniqueConstraint(fields=('proposal_version', 'document_version'), name='proposal_document_once'),
        ),
        migrations.RunSQL(
            sql="""
            CREATE FUNCTION finance_reject_proposal_mutation()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'proposal history is immutable'
                USING ERRCODE = 'check_violation';
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER proposal_version_append_only
            BEFORE UPDATE OR DELETE ON finance_proposalversion
            FOR EACH ROW EXECUTE FUNCTION finance_reject_proposal_mutation();

            CREATE TRIGGER proposal_document_append_only
            BEFORE UPDATE OR DELETE ON finance_proposaldocument
            FOR EACH ROW EXECUTE FUNCTION finance_reject_proposal_mutation();

            CREATE FUNCTION finance_protect_proposal_mode()
            RETURNS trigger AS $$
            BEGIN
                IF OLD.mode IS DISTINCT FROM NEW.mode THEN
                    RAISE EXCEPTION 'proposal mode is immutable'
                    USING ERRCODE = 'check_violation';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER proposal_mode_immutable
            BEFORE UPDATE ON finance_proposal
            FOR EACH ROW EXECUTE FUNCTION finance_protect_proposal_mode();
            """,
            reverse_sql="""
            DROP TRIGGER proposal_mode_immutable ON finance_proposal;
            DROP FUNCTION finance_protect_proposal_mode();
            DROP TRIGGER proposal_document_append_only ON finance_proposaldocument;
            DROP TRIGGER proposal_version_append_only ON finance_proposalversion;
            DROP FUNCTION finance_reject_proposal_mutation();
            """,
        ),
    ]
