# Generated by Django 5.2.16 on 2026-07-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_grant_signed_executor'),
        ('evidence', '0007_revoke_legacy_runtime_execute'),
        ('finance', '0004_emergency_flow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='emergencyratification',
            name='emergency_ratification_provenance',
        ),
        migrations.AddConstraint(
            model_name='emergencyratification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decision', 'OVERDUE'), ('membership__isnull', True), ('outbox_event__isnull', True), ('outcome', 'OVERDUE'), ('signature', ''), ('wallet__isnull', True)), models.Q(('membership__isnull', False), ('outbox_event__isnull', False), ('wallet__isnull', False), models.Q(('signature', ''), _negated=True), models.Q(models.Q(('decision', 'RATIFY'), ('outcome', 'RATIFIED')), models.Q(('decision', 'REJECT'), ('outcome', 'REJECTED')), _connector='OR')), _connector='OR'), name='emergency_ratification_provenance'),
        ),
    ]
