# Generated by Django 5.2.16 on 2026-07-13 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_grant_signed_executor"),
        ("documents", "0001_initial"),
        ("evidence", "0007_revoke_legacy_runtime_execute"),
        ("finance", "0006_emergency_deadline_and_outcome_invariants"),
        ("maintenance", "0008_emergency_authorized_state_invariant"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcceptanceRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("actual_cost_vnd", models.BigIntegerField()),
                ("signature", models.CharField(max_length=132)),
                ("accepted_at", models.DateTimeField()),
                ("acceptance_original", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="documents.documentversion")),
                ("acceptance_redacted", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="documents.documentversion")),
                ("invoice_original", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="documents.documentversion")),
                ("invoice_redacted", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="documents.documentversion")),
                ("membership", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="accounts.organizationmembership")),
                ("outbox_event", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="acceptance_record", to="evidence.blockchainoutboxevent")),
                ("wallet", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="accounts.signerwallet")),
                ("work_order", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="acceptance", to="maintenance.workorder")),
            ],
        ),
        migrations.CreateModel(
            name="PaymentEvidence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bank_reference", models.CharField(max_length=128, unique=True)),
                ("amount_vnd", models.BigIntegerField()),
                ("external_status", models.CharField(choices=[("COMPLETED", "Completed"), ("FAILED", "Failed"), ("REVERSED", "Reversed")], max_length=16)),
                ("completed_at", models.DateTimeField()),
                ("signature", models.CharField(max_length=132)),
                ("recorded_at", models.DateTimeField()),
                ("acceptance", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="payment", to="finance.acceptancerecord")),
                ("outbox_event", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="payment_evidence", to="evidence.blockchainoutboxevent")),
                ("proof_original", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="documents.documentversion")),
                ("proof_redacted", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="documents.documentversion")),
                ("recorder", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="recorded_payments", to="accounts.organizationmembership")),
                ("wallet", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="accounts.signerwallet")),
            ],
        ),
        migrations.CreateModel(
            name="PaymentVerification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("decision", models.CharField(choices=[("VERIFIED", "Verified"), ("REJECTED", "Rejected")], max_length=16)),
                ("reason", models.TextField()),
                ("signature", models.CharField(max_length=132)),
                ("verified_at", models.DateTimeField()),
                ("membership", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payment_verifications", to="accounts.organizationmembership")),
                ("outbox_event", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="payment_verification", to="evidence.blockchainoutboxevent")),
                ("payment", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="verification", to="finance.paymentevidence")),
                ("wallet", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="accounts.signerwallet")),
            ],
        ),
        migrations.AddConstraint(
            model_name="acceptancerecord",
            constraint=models.CheckConstraint(condition=models.Q(("actual_cost_vnd__gt", 0)), name="acceptance_actual_cost_positive"),
        ),
        migrations.AddConstraint(
            model_name="paymentevidence",
            constraint=models.CheckConstraint(condition=models.Q(("amount_vnd__gt", 0)), name="payment_amount_positive"),
        ),
        migrations.RunSQL(
            sql="""
            CREATE FUNCTION finance_reject_acceptance_mutation()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'acceptance records are immutable'
                USING ERRCODE = 'check_violation';
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER acceptance_record_append_only
            BEFORE UPDATE OR DELETE ON finance_acceptancerecord
            FOR EACH ROW EXECUTE FUNCTION finance_reject_acceptance_mutation();

            CREATE FUNCTION finance_reject_payment_evidence_mutation()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'payment evidence is immutable'
                USING ERRCODE = 'check_violation';
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER payment_evidence_append_only
            BEFORE UPDATE OR DELETE ON finance_paymentevidence
            FOR EACH ROW EXECUTE FUNCTION finance_reject_payment_evidence_mutation();

            CREATE FUNCTION finance_reject_payment_verification_mutation()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'payment verifications are immutable'
                USING ERRCODE = 'check_violation';
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER payment_verification_append_only
            BEFORE UPDATE OR DELETE ON finance_paymentverification
            FOR EACH ROW EXECUTE FUNCTION finance_reject_payment_verification_mutation();

            CREATE FUNCTION finance_reject_payment_self_verification()
            RETURNS trigger AS $$
            DECLARE
                recorder_user_id bigint;
                verifier_user_id bigint;
            BEGIN
                SELECT recorder_membership.user_id INTO recorder_user_id
                FROM finance_paymentevidence payment
                JOIN accounts_organizationmembership recorder_membership
                  ON recorder_membership.id = payment.recorder_id
                WHERE payment.id = NEW.payment_id;

                IF NOT FOUND THEN
                    RAISE EXCEPTION 'payment evidence missing for verification'
                    USING ERRCODE = 'foreign_key_violation';
                END IF;

                SELECT verifier_membership.user_id INTO verifier_user_id
                FROM accounts_organizationmembership verifier_membership
                WHERE verifier_membership.id = NEW.membership_id;

                IF NOT FOUND THEN
                    RAISE EXCEPTION 'payment verifier membership missing'
                    USING ERRCODE = 'foreign_key_violation';
                END IF;

                IF recorder_user_id = verifier_user_id THEN
                    RAISE EXCEPTION 'payment verifier must differ from payment recorder'
                    USING ERRCODE = 'check_violation';
                END IF;

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER payment_verification_maker_checker
            BEFORE INSERT ON finance_paymentverification
            FOR EACH ROW EXECUTE FUNCTION finance_reject_payment_self_verification();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS payment_verification_maker_checker ON finance_paymentverification;
            DROP FUNCTION IF EXISTS finance_reject_payment_self_verification();
            DROP TRIGGER IF EXISTS payment_verification_append_only ON finance_paymentverification;
            DROP FUNCTION IF EXISTS finance_reject_payment_verification_mutation();
            DROP TRIGGER IF EXISTS payment_evidence_append_only ON finance_paymentevidence;
            DROP FUNCTION IF EXISTS finance_reject_payment_evidence_mutation();
            DROP TRIGGER IF EXISTS acceptance_record_append_only ON finance_acceptancerecord;
            DROP FUNCTION IF EXISTS finance_reject_acceptance_mutation();
            """,
        ),
    ]
