# Generated by Django 5.2.16 on 2026-07-13 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_grant_signed_executor'),
        ('documents', '0001_initial'),
        ('evidence', '0007_revoke_legacy_runtime_execute'),
        ('finance', '0007_acceptance_and_payment'),
        ('maintenance', '0008_emergency_authorized_state_invariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_fund', to='accounts.building')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceFundEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('OPENING_BALANCE', 'Opening balance'), ('INFLOW', 'Inflow'), ('OUTFLOW', 'Outflow'), ('REVERSAL', 'Reversal'), ('REPLACEMENT', 'Replacement')], max_length=32)),
                ('amount_vnd', models.BigIntegerField()),
                ('evidence_original_hash', models.CharField(blank=True, max_length=64)),
                ('evidence_redacted_hash', models.CharField(blank=True, max_length=64)),
                ('signature', models.CharField(blank=True, max_length=132)),
                ('source_key', models.CharField(max_length=128, unique=True)),
                ('recorded_at', models.DateTimeField()),
                ('evidence_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.documentversion')),
                ('evidence_redacted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.documentversion')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.maintenancefund')),
                ('outbox_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fund_entry', to='evidence.blockchainoutboxevent')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fund_entries', to='finance.proposal')),
                ('recorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_fund_entries', to='accounts.organizationmembership')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.signerwallet')),
            ],
        ),
        migrations.CreateModel(
            name='FundEntryVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=132)),
                ('verified_at', models.DateTimeField()),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fund_verifications', to='accounts.organizationmembership')),
                ('outbox_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fund_entry_verification', to='evidence.blockchainoutboxevent')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.signerwallet')),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='verification', to='finance.maintenancefundentry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicationGateFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_code', models.CharField(max_length=64)),
                ('expected_hash', models.CharField(blank=True, max_length=64)),
                ('actual_hash', models.CharField(blank=True, max_length=64)),
                ('severity', models.CharField(choices=[('BLOCKING', 'Blocking'), ('WARNING', 'Warning')], default='BLOCKING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organizationmembership')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publication_gate_failures', to='finance.proposal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_payload', models.JSONField()),
                ('resident_payload_hash', models.CharField(max_length=64)),
                ('signature', models.CharField(max_length=132)),
                ('prepared_at', models.DateTimeField()),
                ('outbox_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='publication_snapshot', to='evidence.blockchainoutboxevent')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='publication_snapshot', to='finance.proposal')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publication_snapshots', to='accounts.organizationmembership')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.signerwallet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='maintenancefundentry',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fund_entries', to='finance.publicationsnapshot'),
        ),
        migrations.CreateModel(
            name='PublishedLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_cost_vnd', models.BigIntegerField()),
                ('contractor_name', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.maintenancecase')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.paymentevidence')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='published_ledger_entry', to='finance.proposal')),
                ('snapshot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entry', to='finance.publicationsnapshot')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.workorder')),
            ],
        ),
        migrations.AddConstraint(
            model_name='maintenancefundentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount_vnd__gt', 0), ('entry_type__in', ['OPENING_BALANCE', 'INFLOW'])), models.Q(('amount_vnd__lt', 0), ('entry_type', 'OUTFLOW')), models.Q(('entry_type__in', ['REVERSAL', 'REPLACEMENT']), models.Q(('amount_vnd', 0), _negated=True)), _connector='OR'), name='fund_entry_amount_sign'),
        ),
        migrations.AddConstraint(
            model_name='publishedledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('actual_cost_vnd__gt', 0)), name='published_ledger_actual_cost_positive'),
        ),
        migrations.RunSQL(
            sql="""
            CREATE FUNCTION finance_reject_fund_entry_mutation()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'fund entries are immutable'
                USING ERRCODE = 'check_violation';
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER fund_entry_append_only
            BEFORE UPDATE OR DELETE ON finance_maintenancefundentry
            FOR EACH ROW EXECUTE FUNCTION finance_reject_fund_entry_mutation();

            CREATE FUNCTION finance_reject_fund_verification_mutation()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'fund verifications are immutable'
                USING ERRCODE = 'check_violation';
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER fund_verification_append_only
            BEFORE UPDATE OR DELETE ON finance_fundentryverification
            FOR EACH ROW EXECUTE FUNCTION finance_reject_fund_verification_mutation();

            CREATE FUNCTION finance_reject_publication_snapshot_mutation()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'publication snapshots are immutable'
                USING ERRCODE = 'check_violation';
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER publication_snapshot_append_only
            BEFORE UPDATE OR DELETE ON finance_publicationsnapshot
            FOR EACH ROW EXECUTE FUNCTION finance_reject_publication_snapshot_mutation();

            CREATE FUNCTION finance_reject_publication_gate_failure_mutation()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'publication gate failures are immutable'
                USING ERRCODE = 'check_violation';
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER publication_gate_failure_append_only
            BEFORE UPDATE OR DELETE ON finance_publicationgatefailure
            FOR EACH ROW EXECUTE FUNCTION finance_reject_publication_gate_failure_mutation();

            CREATE FUNCTION finance_reject_published_ledger_mutation()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'published ledger entries are immutable'
                USING ERRCODE = 'check_violation';
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER published_ledger_append_only
            BEFORE UPDATE OR DELETE ON finance_publishedledgerentry
            FOR EACH ROW EXECUTE FUNCTION finance_reject_published_ledger_mutation();

            CREATE FUNCTION finance_reject_fund_self_verification()
            RETURNS trigger AS $$
            DECLARE
                recorder_user_id bigint;
                verifier_user_id bigint;
            BEGIN
                SELECT recorder_membership.user_id INTO recorder_user_id
                FROM finance_maintenancefundentry entry
                JOIN accounts_organizationmembership recorder_membership
                  ON recorder_membership.id = entry.recorder_id
                WHERE entry.id = NEW.entry_id;

                IF NOT FOUND THEN
                    RAISE EXCEPTION 'fund entry missing for verification'
                    USING ERRCODE = 'foreign_key_violation';
                END IF;

                SELECT verifier_membership.user_id INTO verifier_user_id
                FROM accounts_organizationmembership verifier_membership
                WHERE verifier_membership.id = NEW.membership_id;

                IF NOT FOUND THEN
                    RAISE EXCEPTION 'fund verifier membership missing'
                    USING ERRCODE = 'foreign_key_violation';
                END IF;

                IF recorder_user_id = verifier_user_id THEN
                    RAISE EXCEPTION 'fund verifier must differ from fund recorder'
                    USING ERRCODE = 'check_violation';
                END IF;

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER fund_verification_maker_checker
            BEFORE INSERT ON finance_fundentryverification
            FOR EACH ROW EXECUTE FUNCTION finance_reject_fund_self_verification();

            CREATE FUNCTION finance_reject_ineligible_publisher()
            RETURNS trigger AS $$
            DECLARE
                publisher_user_id bigint;
                creator_user_id bigint;
                approver_user_id bigint;
                recorder_user_id bigint;
            BEGIN
                SELECT publisher_membership.user_id INTO publisher_user_id
                FROM accounts_organizationmembership publisher_membership
                WHERE publisher_membership.id = NEW.publisher_id;

                IF NOT FOUND THEN
                    RAISE EXCEPTION 'publisher membership missing'
                    USING ERRCODE = 'foreign_key_violation';
                END IF;

                SELECT creator_membership.user_id INTO creator_user_id
                FROM finance_proposal proposal
                JOIN accounts_organizationmembership creator_membership
                  ON creator_membership.id = proposal.creator_membership_id
                WHERE proposal.id = NEW.proposal_id;

                IF NOT FOUND THEN
                    RAISE EXCEPTION 'proposal missing for publication snapshot'
                    USING ERRCODE = 'foreign_key_violation';
                END IF;

                IF publisher_user_id = creator_user_id THEN
                    RAISE EXCEPTION 'publisher must differ from proposal creator'
                    USING ERRCODE = 'check_violation';
                END IF;

                SELECT board_membership.user_id INTO approver_user_id
                FROM finance_proposal proposal
                JOIN finance_proposalversion version
                  ON version.id = proposal.current_version_id
                JOIN finance_approvaldecision decision
                  ON decision.version_id = version.id
                 AND decision.stage = 'BOARD'
                 AND decision.decision = 'APPROVE'
                JOIN accounts_organizationmembership board_membership
                  ON board_membership.id = decision.membership_id
                WHERE proposal.id = NEW.proposal_id
                LIMIT 1;

                IF FOUND AND publisher_user_id = approver_user_id THEN
                    RAISE EXCEPTION 'publisher must differ from board proposal approver'
                    USING ERRCODE = 'check_violation';
                END IF;

                SELECT recorder_membership.user_id INTO recorder_user_id
                FROM finance_proposal proposal
                JOIN maintenance_workorder work_order
                  ON work_order.id = proposal.work_order_id
                JOIN finance_acceptancerecord acceptance
                  ON acceptance.work_order_id = work_order.id
                JOIN finance_paymentevidence payment
                  ON payment.acceptance_id = acceptance.id
                JOIN accounts_organizationmembership recorder_membership
                  ON recorder_membership.id = payment.recorder_id
                WHERE proposal.id = NEW.proposal_id
                LIMIT 1;

                IF FOUND AND publisher_user_id = recorder_user_id THEN
                    RAISE EXCEPTION 'publisher must differ from payment recorder'
                    USING ERRCODE = 'check_violation';
                END IF;

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER publication_snapshot_publisher_dual_control
            BEFORE INSERT ON finance_publicationsnapshot
            FOR EACH ROW EXECUTE FUNCTION finance_reject_ineligible_publisher();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS publication_snapshot_publisher_dual_control ON finance_publicationsnapshot;
            DROP FUNCTION IF EXISTS finance_reject_ineligible_publisher();
            DROP TRIGGER IF EXISTS fund_verification_maker_checker ON finance_fundentryverification;
            DROP FUNCTION IF EXISTS finance_reject_fund_self_verification();
            DROP TRIGGER IF EXISTS published_ledger_append_only ON finance_publishedledgerentry;
            DROP FUNCTION IF EXISTS finance_reject_published_ledger_mutation();
            DROP TRIGGER IF EXISTS publication_gate_failure_append_only ON finance_publicationgatefailure;
            DROP FUNCTION IF EXISTS finance_reject_publication_gate_failure_mutation();
            DROP TRIGGER IF EXISTS publication_snapshot_append_only ON finance_publicationsnapshot;
            DROP FUNCTION IF EXISTS finance_reject_publication_snapshot_mutation();
            DROP TRIGGER IF EXISTS fund_verification_append_only ON finance_fundentryverification;
            DROP FUNCTION IF EXISTS finance_reject_fund_verification_mutation();
            DROP TRIGGER IF EXISTS fund_entry_append_only ON finance_maintenancefundentry;
            DROP FUNCTION IF EXISTS finance_reject_fund_entry_mutation();
            """,
        ),
    ]
