# Generated by Django 5.2.16 on 2026-07-13 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_grant_signed_executor'),
        ('documents', '0001_initial'),
        ('evidence', '0007_revoke_legacy_runtime_execute'),
        ('finance', '0008_fund_and_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('replacement_payload', models.JSONField()),
                ('replacement_payload_hash', models.CharField(max_length=64)),
                ('signature', models.CharField(max_length=132)),
                ('created_at', models.DateTimeField()),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_corrections', to='accounts.organizationmembership')),
                ('original_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='finance.publishedledgerentry')),
                ('outbox_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='correction', to='evidence.blockchainoutboxevent')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.signerwallet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='maintenancefundentry',
            name='correction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fund_entries', to='finance.correction'),
        ),
        migrations.CreateModel(
            name='CorrectionPublicationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_payload', models.JSONField()),
                ('resident_payload_hash', models.CharField(max_length=64)),
                ('signature', models.CharField(max_length=132)),
                ('prepared_at', models.DateTimeField()),
                ('correction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='publication_snapshot', to='finance.correction')),
                ('outbox_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='correction_publication_snapshot', to='evidence.blockchainoutboxevent')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_publication_snapshots', to='accounts.organizationmembership')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.signerwallet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerificationObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('VERIFIED', 'Verified'), ('MISMATCH', 'Mismatch'), ('UNAVAILABLE', 'Unavailable')], max_length=16)),
                ('checked_document_hashes', models.JSONField(default=list)),
                ('checked_chain_event_ids', models.JSONField(default=list)),
                ('details', models.JSONField(default=dict)),
                ('observed_at', models.DateTimeField()),
                ('published_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_observations', to='finance.publishedledgerentry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CorrectionDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('BOARD', 'Management Board'), ('RESIDENT_REP', 'Resident representative')], max_length=16)),
                ('decision', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=8)),
                ('reason', models.TextField()),
                ('signature', models.CharField(max_length=132)),
                ('decided_at', models.DateTimeField()),
                ('correction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='finance.correction')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organizationmembership')),
                ('outbox_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='correction_decision', to='evidence.blockchainoutboxevent')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.signerwallet')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('correction', 'stage'), name='correction_decision_once_per_stage')],
            },
        ),
        migrations.CreateModel(
            name='CorrectionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='EVIDENCE', max_length=32)),
                ('correction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='finance.correction')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.documentversion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('correction', 'version'), name='correction_document_once')],
            },
        ),

        migrations.RunSQL(
            sql="""
            CREATE FUNCTION finance_reject_correction_mutation()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'corrections are immutable'
                USING ERRCODE = 'check_violation';
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER correction_append_only
            BEFORE UPDATE OR DELETE ON finance_correction
            FOR EACH ROW EXECUTE FUNCTION finance_reject_correction_mutation();

            CREATE FUNCTION finance_reject_correction_decision_mutation()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'correction decisions are immutable'
                USING ERRCODE = 'check_violation';
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER correction_decision_append_only
            BEFORE UPDATE OR DELETE ON finance_correctiondecision
            FOR EACH ROW EXECUTE FUNCTION finance_reject_correction_decision_mutation();

            CREATE FUNCTION finance_reject_correction_document_mutation()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'correction documents are immutable'
                USING ERRCODE = 'check_violation';
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER correction_document_append_only
            BEFORE UPDATE OR DELETE ON finance_correctiondocument
            FOR EACH ROW EXECUTE FUNCTION finance_reject_correction_document_mutation();

            CREATE FUNCTION finance_reject_correction_publication_mutation()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'correction publication snapshots are immutable'
                USING ERRCODE = 'check_violation';
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER correction_publication_append_only
            BEFORE UPDATE OR DELETE ON finance_correctionpublicationsnapshot
            FOR EACH ROW EXECUTE FUNCTION finance_reject_correction_publication_mutation();

            CREATE FUNCTION finance_reject_verification_observation_mutation()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'verification observations are immutable'
                USING ERRCODE = 'check_violation';
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER verification_observation_append_only
            BEFORE UPDATE OR DELETE ON finance_verificationobservation
            FOR EACH ROW EXECUTE FUNCTION finance_reject_verification_observation_mutation();

            CREATE FUNCTION finance_reject_ineligible_correction_publisher()
            RETURNS trigger AS $$
            DECLARE
                publisher_user_id bigint;
                creator_user_id bigint;
                proposal_approver_user_id bigint;
                payment_recorder_user_id bigint;
                correction_board_user_id bigint;
                target_proposal_id bigint;
            BEGIN
                SELECT publisher_membership.user_id INTO publisher_user_id
                FROM accounts_organizationmembership publisher_membership
                WHERE publisher_membership.id = NEW.publisher_id;

                IF NOT FOUND THEN
                    RAISE EXCEPTION 'correction publisher membership missing'
                    USING ERRCODE = 'foreign_key_violation';
                END IF;

                SELECT entry.proposal_id INTO target_proposal_id
                FROM finance_correction correction
                JOIN finance_publishedledgerentry entry
                  ON entry.id = correction.original_entry_id
                WHERE correction.id = NEW.correction_id;

                IF NOT FOUND THEN
                    RAISE EXCEPTION 'correction missing for publication snapshot'
                    USING ERRCODE = 'foreign_key_violation';
                END IF;

                SELECT creator_membership.user_id INTO creator_user_id
                FROM finance_proposal proposal
                JOIN accounts_organizationmembership creator_membership
                  ON creator_membership.id = proposal.creator_membership_id
                WHERE proposal.id = target_proposal_id;

                IF FOUND AND publisher_user_id = creator_user_id THEN
                    RAISE EXCEPTION 'correction publisher must differ from proposal creator'
                    USING ERRCODE = 'check_violation';
                END IF;

                SELECT board_membership.user_id INTO proposal_approver_user_id
                FROM finance_proposal proposal
                JOIN finance_proposalversion version
                  ON version.id = proposal.current_version_id
                JOIN finance_approvaldecision decision
                  ON decision.version_id = version.id
                 AND decision.stage = 'BOARD'
                 AND decision.decision = 'APPROVE'
                JOIN accounts_organizationmembership board_membership
                  ON board_membership.id = decision.membership_id
                WHERE proposal.id = target_proposal_id
                LIMIT 1;

                IF FOUND AND publisher_user_id = proposal_approver_user_id THEN
                    RAISE EXCEPTION 'correction publisher must differ from board proposal approver'
                    USING ERRCODE = 'check_violation';
                END IF;

                SELECT recorder_membership.user_id INTO payment_recorder_user_id
                FROM finance_proposal proposal
                JOIN maintenance_workorder work_order
                  ON work_order.id = proposal.work_order_id
                JOIN finance_acceptancerecord acceptance
                  ON acceptance.work_order_id = work_order.id
                JOIN finance_paymentevidence payment
                  ON payment.acceptance_id = acceptance.id
                JOIN accounts_organizationmembership recorder_membership
                  ON recorder_membership.id = payment.recorder_id
                WHERE proposal.id = target_proposal_id
                LIMIT 1;

                IF FOUND AND publisher_user_id = payment_recorder_user_id THEN
                    RAISE EXCEPTION 'correction publisher must differ from payment recorder'
                    USING ERRCODE = 'check_violation';
                END IF;

                SELECT board_membership.user_id INTO correction_board_user_id
                FROM finance_correctiondecision decision
                JOIN accounts_organizationmembership board_membership
                  ON board_membership.id = decision.membership_id
                WHERE decision.correction_id = NEW.correction_id
                  AND decision.stage = 'BOARD'
                  AND decision.decision = 'APPROVE'
                LIMIT 1;

                IF FOUND AND publisher_user_id = correction_board_user_id THEN
                    RAISE EXCEPTION 'correction publisher must differ from correction board approver'
                    USING ERRCODE = 'check_violation';
                END IF;

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER correction_publication_publisher_dual_control
            BEFORE INSERT ON finance_correctionpublicationsnapshot
            FOR EACH ROW EXECUTE FUNCTION finance_reject_ineligible_correction_publisher();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS correction_publication_publisher_dual_control ON finance_correctionpublicationsnapshot;
            DROP FUNCTION IF EXISTS finance_reject_ineligible_correction_publisher();
            DROP TRIGGER IF EXISTS verification_observation_append_only ON finance_verificationobservation;
            DROP FUNCTION IF EXISTS finance_reject_verification_observation_mutation();
            DROP TRIGGER IF EXISTS correction_publication_append_only ON finance_correctionpublicationsnapshot;
            DROP FUNCTION IF EXISTS finance_reject_correction_publication_mutation();
            DROP TRIGGER IF EXISTS correction_document_append_only ON finance_correctiondocument;
            DROP FUNCTION IF EXISTS finance_reject_correction_document_mutation();
            DROP TRIGGER IF EXISTS correction_decision_append_only ON finance_correctiondecision;
            DROP FUNCTION IF EXISTS finance_reject_correction_decision_mutation();
            DROP TRIGGER IF EXISTS correction_append_only ON finance_correction;
            DROP FUNCTION IF EXISTS finance_reject_correction_mutation();
            """,
        ),
    ]
