# Generated by Django 5.2.16 on 2026-07-21 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_corrections_and_observations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correctiondocument',
            name='correction',
        ),
        migrations.RemoveField(
            model_name='maintenancefundentry',
            name='correction',
        ),
        migrations.RemoveField(
            model_name='correctiondecision',
            name='correction',
        ),
        migrations.RemoveField(
            model_name='correctionpublicationsnapshot',
            name='correction',
        ),
        migrations.RemoveField(
            model_name='correctiondecision',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='correctiondecision',
            name='outbox_event',
        ),
        migrations.RemoveField(
            model_name='correctiondecision',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='correctiondocument',
            name='version',
        ),
        migrations.RemoveField(
            model_name='correctionpublicationsnapshot',
            name='outbox_event',
        ),
        migrations.RemoveField(
            model_name='correctionpublicationsnapshot',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='correctionpublicationsnapshot',
            name='wallet',
        ),
        migrations.DeleteModel(
            name='Correction',
        ),
        migrations.DeleteModel(
            name='CorrectionDecision',
        ),
        migrations.DeleteModel(
            name='CorrectionDocument',
        ),
        migrations.DeleteModel(
            name='CorrectionPublicationSnapshot',
        ),
    ]
