# Generated by Django 5.2.16 on 2026-07-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_remove_correctiondocument_correction_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DROP TRIGGER IF EXISTS proposal_mode_immutable ON finance_proposal;
                DROP FUNCTION IF EXISTS finance_protect_proposal_mode();
            """,
            reverse_sql="""
                CREATE FUNCTION finance_protect_proposal_mode()
                RETURNS trigger AS $$
                BEGIN
                    IF OLD.mode IS DISTINCT FROM NEW.mode THEN
                        RAISE EXCEPTION 'Proposal mode is immutable.';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;
                CREATE TRIGGER proposal_mode_immutable
                BEFORE UPDATE ON finance_proposal
                FOR EACH ROW EXECUTE FUNCTION finance_protect_proposal_mode();
            """,
        ),
        migrations.RemoveField(
            model_name='emergencyratification',
            name='authorization',
        ),
        migrations.RemoveField(
            model_name='emergencyratification',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='emergencyratification',
            name='outbox_event',
        ),
        migrations.RemoveField(
            model_name='emergencyratification',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='mode',
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In review'), ('NORMAL_AUTHORIZED', 'Normal authorized'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=24),
        ),
        migrations.DeleteModel(
            name='EmergencyAuthorization',
        ),
        migrations.DeleteModel(
            name='EmergencyRatification',
        ),
    ]
