# Generated by Django 5.2.16 on 2026-07-21 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_remove_emergencyratification_authorization_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApprovalDecision',
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION finance_reject_ineligible_publisher()
            RETURNS trigger AS $$
            DECLARE
                publisher_user_id bigint;
                creator_user_id bigint;
                recorder_user_id bigint;
            BEGIN
                SELECT user_id INTO publisher_user_id
                FROM accounts_organizationmembership WHERE id = NEW.publisher_id;
                IF NOT FOUND THEN
                    RAISE EXCEPTION 'publisher membership missing'
                    USING ERRCODE = 'foreign_key_violation';
                END IF;

                SELECT creator_membership.user_id INTO creator_user_id
                FROM finance_proposal proposal
                JOIN accounts_organizationmembership creator_membership
                  ON creator_membership.id = proposal.creator_membership_id
                WHERE proposal.id = NEW.proposal_id;
                IF NOT FOUND THEN
                    RAISE EXCEPTION 'proposal missing for publication snapshot'
                    USING ERRCODE = 'foreign_key_violation';
                END IF;
                IF publisher_user_id = creator_user_id THEN
                    RAISE EXCEPTION 'publisher must differ from proposal creator'
                    USING ERRCODE = 'check_violation';
                END IF;

                SELECT recorder_membership.user_id INTO recorder_user_id
                FROM finance_proposal proposal
                JOIN maintenance_workorder work_order ON work_order.id = proposal.work_order_id
                JOIN finance_acceptancerecord acceptance ON acceptance.work_order_id = work_order.id
                JOIN finance_paymentevidence payment ON payment.acceptance_id = acceptance.id
                JOIN accounts_organizationmembership recorder_membership
                  ON recorder_membership.id = payment.recorder_id
                WHERE proposal.id = NEW.proposal_id LIMIT 1;
                IF FOUND AND publisher_user_id = recorder_user_id THEN
                    RAISE EXCEPTION 'publisher must differ from payment recorder'
                    USING ERRCODE = 'check_violation';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE OR REPLACE FUNCTION finance_reject_ineligible_correction_publisher()
            RETURNS trigger AS $$
            DECLARE
                publisher_user_id bigint;
                creator_user_id bigint;
                payment_recorder_user_id bigint;
                correction_board_user_id bigint;
                target_proposal_id bigint;
            BEGIN
                SELECT user_id INTO publisher_user_id
                FROM accounts_organizationmembership WHERE id = NEW.publisher_id;
                IF NOT FOUND THEN
                    RAISE EXCEPTION 'correction publisher membership missing'
                    USING ERRCODE = 'foreign_key_violation';
                END IF;

                SELECT entry.proposal_id INTO target_proposal_id
                FROM finance_correction correction
                JOIN finance_publishedledgerentry entry ON entry.id = correction.original_entry_id
                WHERE correction.id = NEW.correction_id;
                IF NOT FOUND THEN
                    RAISE EXCEPTION 'correction missing for publication snapshot'
                    USING ERRCODE = 'foreign_key_violation';
                END IF;

                SELECT creator_membership.user_id INTO creator_user_id
                FROM finance_proposal proposal
                JOIN accounts_organizationmembership creator_membership
                  ON creator_membership.id = proposal.creator_membership_id
                WHERE proposal.id = target_proposal_id;
                IF FOUND AND publisher_user_id = creator_user_id THEN
                    RAISE EXCEPTION 'correction publisher must differ from proposal creator'
                    USING ERRCODE = 'check_violation';
                END IF;

                SELECT recorder_membership.user_id INTO payment_recorder_user_id
                FROM finance_proposal proposal
                JOIN maintenance_workorder work_order ON work_order.id = proposal.work_order_id
                JOIN finance_acceptancerecord acceptance ON acceptance.work_order_id = work_order.id
                JOIN finance_paymentevidence payment ON payment.acceptance_id = acceptance.id
                JOIN accounts_organizationmembership recorder_membership
                  ON recorder_membership.id = payment.recorder_id
                WHERE proposal.id = target_proposal_id LIMIT 1;
                IF FOUND AND publisher_user_id = payment_recorder_user_id THEN
                    RAISE EXCEPTION 'correction publisher must differ from payment recorder'
                    USING ERRCODE = 'check_violation';
                END IF;

                SELECT board_membership.user_id INTO correction_board_user_id
                FROM finance_correctiondecision decision
                JOIN accounts_organizationmembership board_membership
                  ON board_membership.id = decision.membership_id
                WHERE decision.correction_id = NEW.correction_id
                  AND decision.stage = 'BOARD' AND decision.decision = 'APPROVE'
                LIMIT 1;
                IF FOUND AND publisher_user_id = correction_board_user_id THEN
                    RAISE EXCEPTION 'correction publisher must differ from correction board approver'
                    USING ERRCODE = 'check_violation';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
