# Generated by Django 5.2.16 on 2026-07-21 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_signerauthorizationrequest_requested_by_and_more'),
        ('finance', '0012_delete_approvaldecision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptancerecord',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.managementmembership'),
        ),
        migrations.AlterField(
            model_name='fundentryverification',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fund_verifications', to='accounts.managementmembership'),
        ),
        migrations.AlterField(
            model_name='maintenancefundentry',
            name='recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_fund_entries', to='accounts.managementmembership'),
        ),
        migrations.AlterField(
            model_name='paymentevidence',
            name='recorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_payments', to='accounts.managementmembership'),
        ),
        migrations.AlterField(
            model_name='paymentverification',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_verifications', to='accounts.managementmembership'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='creator_membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.managementmembership'),
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='creator_membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.managementmembership'),
        ),
        migrations.AlterField(
            model_name='publicationgatefailure',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.managementmembership'),
        ),
        migrations.AlterField(
            model_name='publicationsnapshot',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publication_snapshots', to='accounts.managementmembership'),
        ),
    ]
