# Generated by Django 5.2.16 on 2026-07-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_acceptancerecord_membership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalversion',
            name='fund_code',
            field=models.CharField(default='GENERAL', max_length=32),
        ),
    ]
