# Generated by Django 5.2.16 on 2026-07-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_alter_proposalversion_fund_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceptancerecord',
            old_name='work_order',
            new_name='case',
        ),
        migrations.RenameField(
            model_name='proposal',
            old_name='work_order',
            new_name='case',
        ),
    ]
