# Generated by Django 5.2.16 on 2026-07-21 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_rename_work_order_acceptancerecord_case_and_more'),
        ('maintenance', '0016_issuereport_declined_at_issuereport_declined_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptancerecord',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='acceptance', to='maintenance.maintenancecase'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='proposal', to='maintenance.maintenancecase'),
        ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION finance_reject_ineligible_publisher()
            RETURNS trigger AS $$
            DECLARE publisher_user_id bigint; creator_user_id bigint; recorder_user_id bigint;
            BEGIN
                SELECT publisher.user_id INTO publisher_user_id
                FROM accounts_managementmembership publisher WHERE publisher.id = NEW.publisher_id;
                IF NOT FOUND THEN RAISE EXCEPTION 'publisher membership missing' USING ERRCODE = 'foreign_key_violation'; END IF;
                SELECT creator.user_id INTO creator_user_id
                FROM finance_proposal proposal
                JOIN accounts_managementmembership creator ON creator.id = proposal.creator_membership_id
                WHERE proposal.id = NEW.proposal_id;
                IF NOT FOUND THEN RAISE EXCEPTION 'proposal missing for publication snapshot' USING ERRCODE = 'foreign_key_violation'; END IF;
                IF publisher_user_id = creator_user_id THEN RAISE EXCEPTION 'publisher must differ from proposal creator' USING ERRCODE = 'check_violation'; END IF;
                SELECT recorder.user_id INTO recorder_user_id
                FROM finance_proposal proposal
                JOIN finance_acceptancerecord acceptance ON acceptance.case_id = proposal.case_id
                JOIN finance_paymentevidence payment ON payment.acceptance_id = acceptance.id
                JOIN accounts_managementmembership recorder ON recorder.id = payment.recorder_id
                WHERE proposal.id = NEW.proposal_id LIMIT 1;
                IF FOUND AND publisher_user_id = recorder_user_id THEN RAISE EXCEPTION 'publisher must differ from payment recorder' USING ERRCODE = 'check_violation'; END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """,
            migrations.RunSQL.noop,
        ),
    ]
