# Generated by Django 5.2.16 on 2026-07-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_alter_acceptancerecord_case_alter_proposal_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishedledgerentry',
            name='work_order',
        ),
    ]
