# Generated by Django 5.2.16 on 2026-07-21 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_breakglasssession_authorizing_membership_and_more'),
        ('finance', '0017_remove_publishedledgerentry_work_order'),
        ('maintenance', '0018_alter_completionrating_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='accounts.building'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_proposals', to='accounts.managementmembership'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='decision_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='expected_schedule',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='proposed_action',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='case',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposal', to='maintenance.maintenancecase'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('NOT_PROCEEDING', 'Not proceeding'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='DRAFT', max_length=24),
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='creator_signature',
            field=models.CharField(blank=True, max_length=132),
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='creator_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.signerwallet'),
        ),
    ]
