# Generated by Django 5.2.16 on 2026-07-21 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_breakglasssession_authorizing_membership_and_more'),
        ('finance', '0018_proposal_building_proposal_closed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='accounts.building'),
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='expected_schedule',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='proposed_action',
            field=models.TextField(),
        ),
    ]
