# Generated by Django 5.2.16 on 2026-07-21 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_breakglasssession_authorizing_membership_and_more'),
        ('documents', '0003_alter_document_kind'),
        ('evidence', '0017_alter_blockchainoutboxevent_event_type'),
        ('finance', '0019_alter_proposal_building_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentevidence',
            name='acceptance',
        ),
        migrations.RemoveField(
            model_name='paymentevidence',
            name='outbox_event',
        ),
        migrations.RemoveField(
            model_name='paymentevidence',
            name='proof_original',
        ),
        migrations.RemoveField(
            model_name='paymentevidence',
            name='proof_redacted',
        ),
        migrations.RemoveField(
            model_name='paymentevidence',
            name='recorder',
        ),
        migrations.RemoveField(
            model_name='paymentevidence',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='paymentverification',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='paymentverification',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='paymentverification',
            name='outbox_event',
        ),
        migrations.RemoveField(
            model_name='paymentverification',
            name='wallet',
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_vnd', models.BigIntegerField()),
                ('payee_name', models.CharField(max_length=255)),
                ('bank_reference', models.CharField(max_length=64)),
                ('transfer_recorded_at', models.DateTimeField()),
                ('ack_kind', models.CharField(choices=[('MANAGEMENT_UPLOAD', 'Management-uploaded evidence'), ('PAYEE_LINK', 'Payee link (reserved)')], default='MANAGEMENT_UPLOAD', max_length=24)),
                ('ack_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ack_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.documentversion')),
                ('ack_recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.managementmembership')),
                ('ack_redacted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.documentversion')),
                ('outbox_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement', to='evidence.blockchainoutboxevent')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement', to='finance.proposal')),
                ('transfer_original', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.documentversion')),
                ('transfer_recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.managementmembership')),
                ('transfer_redacted', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.documentversion')),
            ],
        ),
        migrations.AlterField(
            model_name='publishedledgerentry',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.settlement'),
        ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION finance_reject_ineligible_publisher()
            RETURNS trigger AS $$
            DECLARE publisher_user_id bigint; creator_user_id bigint; recorder_user_id bigint;
            BEGIN
                SELECT user_id INTO publisher_user_id FROM accounts_managementmembership WHERE id = NEW.publisher_id;
                SELECT creator.user_id INTO creator_user_id
                FROM finance_proposal proposal
                JOIN accounts_managementmembership creator ON creator.id = proposal.creator_membership_id
                WHERE proposal.id = NEW.proposal_id;
                IF publisher_user_id = creator_user_id THEN
                    RAISE EXCEPTION 'publisher must differ from proposal creator' USING ERRCODE = 'check_violation';
                END IF;
                SELECT recorder.user_id INTO recorder_user_id
                FROM finance_settlement settlement
                JOIN accounts_managementmembership recorder ON recorder.id = settlement.transfer_recorded_by_id
                WHERE settlement.proposal_id = NEW.proposal_id;
                IF FOUND AND publisher_user_id = recorder_user_id THEN
                    RAISE EXCEPTION 'publisher must differ from settlement recorder' USING ERRCODE = 'check_violation';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """,
            migrations.RunSQL.noop,
        ),
        migrations.DeleteModel(
            name='AcceptanceRecord',
        ),
        migrations.DeleteModel(
            name='PaymentVerification',
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.CheckConstraint(condition=models.Q(('settled_at__isnull', True), models.Q(('ack_recorded_at__isnull', False), ('outbox_event__isnull', False)), _connector='OR'), name='settlement_requires_both_evidence_sides'),
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.CheckConstraint(condition=models.Q(('amount_vnd__gt', 0)), name='settlement_amount_positive'),
        ),
        migrations.DeleteModel(
            name='PaymentEvidence',
        ),
    ]
