# Generated by Django 5.2.16 on 2026-07-21 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_offchain_ledger_and_fund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalversion',
            name='creator_wallet',
        ),
    ]
