# Generated by Django 5.2.16 on 2026-07-22 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_allow_fund_self_verification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancefundentry',
            name='evidence_redacted',
        ),
        migrations.RemoveField(
            model_name='maintenancefundentry',
            name='evidence_redacted_hash',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='ack_redacted',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='transfer_redacted',
        ),
    ]
