# Generated by Django 5.2.16 on 2026-07-22 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_remove_maintenancefundentry_evidence_redacted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancefundentry',
            old_name='evidence_original',
            new_name='evidence',
        ),
        migrations.RenameField(
            model_name='maintenancefundentry',
            old_name='evidence_original_hash',
            new_name='evidence_hash',
        ),
        migrations.RenameField(
            model_name='settlement',
            old_name='ack_original',
            new_name='ack',
        ),
        migrations.RenameField(
            model_name='settlement',
            old_name='transfer_original',
            new_name='transfer',
        ),
    ]
