# Generated by Django 5.2.16 on 2026-08-14 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_rename_evidence_original_maintenancefundentry_evidence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalversion',
            name='fund_code',
        ),
    ]
