# Generated by Django 5.2.16 on 2026-08-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0028_single_sided_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='public_token',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
