# Generated by Django 5.2.16 on 2026-08-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0029_proposal_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalversion',
            name='expected_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='expected_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
