# Generated by Django 5.2.16 on 2026-08-16 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_purge_totp_secrets'),
        ('finance', '0030_proposalversion_expected_end_and_more'),
        ('maintenance', '0024_maintenancecase_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
                ('amount_vnd', models.BigIntegerField()),
                ('minimum_vnd', models.BigIntegerField()),
                ('central_vnd', models.BigIntegerField()),
                ('maximum_vnd', models.BigIntegerField()),
                ('reasoning', models.TextField()),
                ('source', models.CharField(choices=[('predicted', 'Predicted'), ('fallback', 'Fallback')], default='predicted', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_predictions', to='accounts.building')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_predictions', to='maintenance.maintenancecase')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_predictions', to='accounts.managementmembership')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_vnd__gt', 0)), name='price_prediction_amount_positive'), models.CheckConstraint(condition=models.Q(('central_vnd__gt', 0), ('maximum_vnd__gt', 0), ('minimum_vnd__gt', 0)), name='price_prediction_band_positive')],
            },
        ),
    ]
