# Generated by Django 5.2.16 on 2026-08-16 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0031_priceprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceprediction',
            name='proposal_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_prediction', to='finance.proposalversion'),
        ),
    ]
