"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from lamto.config.secrets import coalesce_secret

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "").lower() in {"1", "true", "yes"}

ALLOWED_HOSTS = [h for h in os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1,testserver").split(",") if h]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.postgres',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'lamto.accounts',
    'lamto.audit',
    'lamto.documents',
    'lamto.finance',
    'lamto.gate',
    'lamto.evidence',
    'lamto.maintenance',
    'lamto.web',
    'lamto.notifications',
    'lamto.config',
    'rest_framework',
    'knox',
    'drf_spectacular',
    'lamto.api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'lamto.accounts.middleware.StaffSecurityMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lamto.config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lamto.config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ["POSTGRES_DB"],
        "USER": os.environ["POSTGRES_USER"],
        "PASSWORD": os.environ["POSTGRES_PASSWORD"],
        "HOST": os.environ["POSTGRES_HOST"],
        "PORT": os.environ["POSTGRES_PORT"],
    }
}

# Optional isolated alias for restore drills (ops/backup/restore-drill.sh).
# When DJANGO_RESTORE_DB_NAME is set, verify_integrity --database restored
# targets the restored database rather than the live default alias.
if os.environ.get("DJANGO_RESTORE_DB_NAME"):
    DATABASES["restored"] = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ["DJANGO_RESTORE_DB_NAME"],
        "USER": os.environ.get("DJANGO_RESTORE_DB_USER", os.environ["POSTGRES_USER"]),
        "PASSWORD": os.environ.get(
            "DJANGO_RESTORE_DB_PASSWORD", os.environ["POSTGRES_PASSWORD"]
        ),
        "HOST": os.environ.get("DJANGO_RESTORE_DB_HOST", os.environ["POSTGRES_HOST"]),
        "PORT": os.environ.get("DJANGO_RESTORE_DB_PORT", os.environ["POSTGRES_PORT"]),
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
# Vietnamese-first product surface; English msgids remain the translation source.

LANGUAGE_CODE = "vi"

LANGUAGES = [
    ("vi", "Tiếng Việt"),
    ("en", "English"),
]

LOCALE_PATHS = [BASE_DIR.parent.parent / "locale"]

TIME_ZONE = "Asia/Ho_Chi_Minh"

USE_I18N = True

USE_TZ = True

# Shared staff/resident datetime display (day-first, 24h, Asia/Ho_Chi_Minh).
SHORT_DATETIME_FORMAT = r"d/m/Y H:i"
DATETIME_FORMAT = r"d/m/Y H:i"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "accounts.User"
AUTHENTICATION_BACKENDS = ["lamto.accounts.backends.PhoneOrEmailBackend"]

DOCUMENT_MAX_UPLOAD_BYTES = int(os.getenv("DOCUMENT_MAX_UPLOAD_BYTES", 20 * 1024 * 1024))
DOCUMENT_SPOOL_MAX_BYTES = int(os.getenv("DOCUMENT_SPOOL_MAX_BYTES", 1024 * 1024))
DOCUMENT_QUARANTINE_RETENTION_DAYS = int(os.getenv("DOCUMENT_QUARANTINE_RETENTION_DAYS", 30))
CLAMAV_HOST = os.environ["CLAMAV_HOST"]
CLAMAV_PORT = os.environ["CLAMAV_PORT"]
AI_TRIAGE_URL = os.environ["AI_TRIAGE_URL"]
AI_TRIAGE_TOKEN = os.environ["AI_TRIAGE_TOKEN"]
AI_TRIAGE_TIMEOUT_SECONDS = float(os.getenv("AI_TRIAGE_TIMEOUT_SECONDS", "5"))
AI_TRIAGE_ALLOW_HTTP = os.getenv("AI_TRIAGE_ALLOW_HTTP", "").lower() in {"1", "true", "yes"}
BLOCKCHAIN_CHAIN_ID = int(os.getenv("BLOCKCHAIN_CHAIN_ID", os.getenv("CHAIN_ID", "1337")))
PLATFORM_SIGNER_PRIVATE_KEY = os.getenv("PLATFORM_SIGNER_PRIVATE_KEY", "")
EVIDENCE_CONTRACT_ADDRESS = (
    os.getenv("EVIDENCE_CONTRACT_ADDRESS")
    or os.getenv("CHAIN_CONTRACT_ADDRESS")
    or "0x" + "00" * 20
)
BLOCKCHAIN_RPC_URL = os.getenv(
    "BLOCKCHAIN_RPC_URL", os.getenv("CHAIN_RPC_URL", "http://127.0.0.1:8545")
)
BLOCKCHAIN_RELAYER_PRIVATE_KEY = coalesce_secret(
    os.getenv("BLOCKCHAIN_RELAYER_PRIVATE_KEY") or os.getenv("CHAIN_SIGNER_PRIVATE_KEY")
)
BLOCKCHAIN_CONTRACT_OWNER_PRIVATE_KEY = coalesce_secret(
    os.getenv("BLOCKCHAIN_CONTRACT_OWNER_PRIVATE_KEY")
)
# settings.BASE_DIR is src/lamto; project root is two parents up.
_PROJECT_ROOT = BASE_DIR.parent.parent
EVIDENCE_REGISTRY_ABI_PATH = os.getenv(
    "EVIDENCE_REGISTRY_ABI_PATH",
    str(
        _PROJECT_ROOT
        / "chain"
        / "out"
        / "EvidenceRegistry.sol"
        / "EvidenceRegistry.json"
    ),
)
EVIDENCE_WRITE_SECRET = os.getenv("EVIDENCE_WRITE_SECRET") or SECRET_KEY

# Anchoring transport (spec 5.2): "besu" performs the chain round-trip;
# "disabled" settles outbox events locally as LOCAL — honest, never CONFIRMED.
EVIDENCE_ANCHORING_BACKEND = os.getenv("EVIDENCE_ANCHORING_BACKEND", "besu")
if EVIDENCE_ANCHORING_BACKEND not in {"besu", "disabled"}:
    from django.core.exceptions import ImproperlyConfigured

    raise ImproperlyConfigured(
        "EVIDENCE_ANCHORING_BACKEND must be 'besu' or 'disabled', got "
        f"{EVIDENCE_ANCHORING_BACKEND!r}."
    )

STORAGES = {
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
    "private": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": os.environ["PRIVATE_STORAGE_BUCKET"],
            "endpoint_url": os.environ["PRIVATE_STORAGE_ENDPOINT_URL"],
            "access_key": os.environ["PRIVATE_STORAGE_ACCESS_KEY"],
            "secret_key": os.environ["PRIVATE_STORAGE_SECRET_KEY"],
            "region_name": os.getenv("PRIVATE_STORAGE_REGION", "us-east-1"),
            "file_overwrite": False,
            "default_acl": None,
            "querystring_auth": True,
        },
    }
}


LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

# Local deploy-check defaults; production sets these via environment.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Notifications / email (override in production)
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND", "django.core.mail.backends.locmem.EmailBackend"
)
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@lamto.local")

# --- Push notifications (spec 7): FCM via firebase-admin ---
# Path to a service-account JSON; never committed. Push is off unless both are set.
FIREBASE_CREDENTIALS = os.getenv("FIREBASE_CREDENTIALS", "")
PUSH_ENABLED = (
    os.getenv("PUSH_ENABLED", "").lower() in {"1", "true", "yes"} and bool(FIREBASE_CREDENTIALS)
)
PUSH_DAILY_CAP_PER_CATEGORY = int(os.getenv("PUSH_DAILY_CAP_PER_CATEGORY", "10"))


# --- Security: password hashing, sessions, MFA-related defaults ---
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_HTTPONLY = False  # must be readable by browser forms
CSRF_COOKIE_SAMESITE = "Lax"
# Secure cookies when not in DEBUG (production / deploy-check).
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
# Required when the browser Origin is a reverse-proxy / Cloudflare tunnel host
# (Django 4+ Origin check). Comma-separated full origins, e.g. https://xyz.trycloudflare.com
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")
    if o.strip()
]

# MFA / re-auth
LAMTO_REAUTH_MAX_AGE_SECONDS = int(os.getenv("LAMTO_REAUTH_MAX_AGE_SECONDS", "300"))
LAMTO_AUTH_THROTTLE_MAX_FAILURES = int(os.getenv("LAMTO_AUTH_THROTTLE_MAX_FAILURES", "5"))
LAMTO_AUTH_THROTTLE_WINDOW_SECONDS = int(
    os.getenv("LAMTO_AUTH_THROTTLE_WINDOW_SECONDS", str(15 * 60))
)

# Backup / ops markers (private operations bucket may share private storage)
BACKUP_OPS_PREFIX = os.getenv("BACKUP_OPS_PREFIX", "ops/backups")
WALG_S3_PREFIX = os.getenv("WALG_S3_PREFIX", "")

# Pilot seed fixtures (non-production only). seed_pilot --fixture refuses when false.
PILOT_ALLOW_FIXTURES = os.getenv("PILOT_ALLOW_FIXTURES", "false").lower() in {
    "1",
    "true",
    "yes",
}

# --- Gate recognition (docs/superpowers/specs/2026-07-22-gate-recognition-design.md) ---
# Logs identity; authorizes nothing. No gate capture image is ever stored.
GATE_EVENT_RETENTION_HOURS = int(os.getenv("GATE_EVENT_RETENTION_HOURS", "24"))
GATE_ENROLLMENT_PHOTO_TTL_HOURS = int(
    os.getenv("GATE_ENROLLMENT_PHOTO_TTL_HOURS", "72")
)
GATE_CREDENTIAL_ROTATION_GRACE_HOURS = int(
    os.getenv("GATE_CREDENTIAL_ROTATION_GRACE_HOURS", "24")
)
# UNVALIDATED PILOT STARTING POINT — NOT a production default. InsightFace's own
# clustering tooling defaults to cosine 0.48, so this is deliberately permissive.
# Calibrate per building before any pilot: manage.py calibrate_gate_threshold.
GATE_FACE_MATCH_THRESHOLD = float(os.getenv("GATE_FACE_MATCH_THRESHOLD", "0.38"))
# Image-quality gates. Also unvalidated starting points; calibrated with the threshold.
GATE_MAX_FACE_UPLOAD_BYTES = int(
    os.getenv("GATE_MAX_FACE_UPLOAD_BYTES", str(8 * 1024 * 1024))
)
GATE_MIN_FACE_PIXELS = int(os.getenv("GATE_MIN_FACE_PIXELS", "80"))
GATE_MIN_FACE_DET_SCORE = float(os.getenv("GATE_MIN_FACE_DET_SCORE", "0.6"))
GATE_MIN_FACE_SHARPNESS = float(os.getenv("GATE_MIN_FACE_SHARPNESS", "40"))
# Dotted path to the FaceEmbedder implementation. Empty until Task 13 lands the
# production embedder; get_embedder() raises rather than guessing.
GATE_FACE_EMBEDDER = os.getenv(
    "GATE_FACE_EMBEDDER", "lamto.gate.embedding.InsightFaceEmbedder"
)
GATE_EMBEDDING_KEY = coalesce_secret(os.getenv("GATE_EMBEDDING_KEY"), SECRET_KEY)

# --- Resident API (spec 3): DRF + knox tokens + OpenAPI schema ---
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "lamto.api.authentication.ResidentTokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_RENDERER_CLASSES": ["rest_framework.renderers.JSONRenderer"],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "lamto.api.problems.problem_exception_handler",
}

REST_KNOX = {
    "TOKEN_TTL": timedelta(days=30),  # spec 3.2: TTL 30 days
    "AUTO_REFRESH": True,  # spec 3.2: sliding refresh on use
}

SPECTACULAR_SETTINGS = {
    "TITLE": "LamTo Resident API",
    "VERSION": "v1",
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX": "/api/v1",
    "COMPONENT_SPLIT_REQUEST": True,
}

# Access/error logs must never retain signed download tokens (spec 3.6).
# DownloadTokenLogFilter redacts /api/v1/documents/<token> path segments.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "scrub_download_tokens": {
            "()": "lamto.config.log_filters.DownloadTokenLogFilter",
        },
    },
    "formatters": {
        "simple": {
            "format": "{levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "filters": ["scrub_download_tokens"],
            "formatter": "simple",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django.server": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}
