"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "").lower() in {"1", "true", "yes"}

ALLOWED_HOSTS = [h for h in os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1,testserver").split(",") if h]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'lamto.accounts',
    'lamto.audit',
    'lamto.documents',
    'lamto.finance',
    'lamto.evidence',
    'lamto.maintenance',
    'lamto.web',
    'lamto.notifications',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lamto.config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lamto.config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ["POSTGRES_DB"],
        "USER": os.environ["POSTGRES_USER"],
        "PASSWORD": os.environ["POSTGRES_PASSWORD"],
        "HOST": os.environ["POSTGRES_HOST"],
        "PORT": os.environ["POSTGRES_PORT"],
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Asia/Ho_Chi_Minh"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "accounts.User"

DOCUMENT_MAX_UPLOAD_BYTES = int(os.getenv("DOCUMENT_MAX_UPLOAD_BYTES", 20 * 1024 * 1024))
DOCUMENT_SPOOL_MAX_BYTES = int(os.getenv("DOCUMENT_SPOOL_MAX_BYTES", 1024 * 1024))
DOCUMENT_QUARANTINE_RETENTION_DAYS = int(os.getenv("DOCUMENT_QUARANTINE_RETENTION_DAYS", 30))
CLAMAV_HOST = os.environ["CLAMAV_HOST"]
CLAMAV_PORT = os.environ["CLAMAV_PORT"]
AI_TRIAGE_URL = os.environ["AI_TRIAGE_URL"]
AI_TRIAGE_TOKEN = os.environ["AI_TRIAGE_TOKEN"]
AI_TRIAGE_TIMEOUT_SECONDS = float(os.getenv("AI_TRIAGE_TIMEOUT_SECONDS", "5"))
AI_TRIAGE_ALLOW_HTTP = os.getenv("AI_TRIAGE_ALLOW_HTTP", "").lower() in {"1", "true", "yes"}
BLOCKCHAIN_CHAIN_ID = int(os.getenv("BLOCKCHAIN_CHAIN_ID", os.getenv("CHAIN_ID", "1337")))
EVIDENCE_CONTRACT_ADDRESS = (
    os.getenv("EVIDENCE_CONTRACT_ADDRESS")
    or os.getenv("CHAIN_CONTRACT_ADDRESS")
    or "0x" + "00" * 20
)
WALLET_REGISTRATION_TTL_SECONDS = int(os.getenv("WALLET_REGISTRATION_TTL_SECONDS", "600"))
BLOCKCHAIN_RPC_URL = os.getenv(
    "BLOCKCHAIN_RPC_URL", os.getenv("CHAIN_RPC_URL", "http://127.0.0.1:8545")
)
BLOCKCHAIN_RELAYER_PRIVATE_KEY = os.getenv(
    "BLOCKCHAIN_RELAYER_PRIVATE_KEY", os.getenv("CHAIN_SIGNER_PRIVATE_KEY", "")
)
BLOCKCHAIN_CONTRACT_OWNER_PRIVATE_KEY = os.getenv("BLOCKCHAIN_CONTRACT_OWNER_PRIVATE_KEY", "")
# settings.BASE_DIR is src/lamto; project root is two parents up.
_PROJECT_ROOT = BASE_DIR.parent.parent
EVIDENCE_REGISTRY_ABI_PATH = os.getenv(
    "EVIDENCE_REGISTRY_ABI_PATH",
    str(
        _PROJECT_ROOT
        / "chain"
        / "out"
        / "EvidenceRegistry.sol"
        / "EvidenceRegistry.json"
    ),
)
EVIDENCE_WRITE_SECRET = os.getenv("EVIDENCE_WRITE_SECRET") or SECRET_KEY

STORAGES = {
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
    "private": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": os.environ["PRIVATE_STORAGE_BUCKET"],
            "endpoint_url": os.environ["PRIVATE_STORAGE_ENDPOINT_URL"],
            "access_key": os.environ["PRIVATE_STORAGE_ACCESS_KEY"],
            "secret_key": os.environ["PRIVATE_STORAGE_SECRET_KEY"],
            "region_name": os.getenv("PRIVATE_STORAGE_REGION", "us-east-1"),
            "file_overwrite": False,
            "default_acl": None,
            "querystring_auth": True,
        },
    }
}


LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

# Local deploy-check defaults; production sets these via environment.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Notifications / email (override in production)
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND", "django.core.mail.backends.locmem.EmailBackend"
)
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@lamto.local")


# --- Security: password hashing, sessions, MFA-related defaults ---
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_HTTPONLY = False  # must be readable by browser forms
CSRF_COOKIE_SAMESITE = "Lax"
# Secure cookies when not in DEBUG (production / deploy-check).
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# MFA / re-auth
LAMTO_REAUTH_MAX_AGE_SECONDS = int(os.getenv("LAMTO_REAUTH_MAX_AGE_SECONDS", "300"))
LAMTO_AUTH_THROTTLE_MAX_FAILURES = int(os.getenv("LAMTO_AUTH_THROTTLE_MAX_FAILURES", "5"))
LAMTO_AUTH_THROTTLE_WINDOW_SECONDS = int(
    os.getenv("LAMTO_AUTH_THROTTLE_WINDOW_SECONDS", str(15 * 60))
)
LAMTO_BREAK_GLASS_MAX_MINUTES = int(os.getenv("LAMTO_BREAK_GLASS_MAX_MINUTES", "60"))

# Backup / ops markers (private operations bucket may share private storage)
BACKUP_OPS_PREFIX = os.getenv("BACKUP_OPS_PREFIX", "ops/backups")
WALG_S3_PREFIX = os.getenv("WALG_S3_PREFIX", "")
