# Generated by Django 5.2.16 on 2026-07-13 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=255)),
                ('event_code', models.CharField(blank=True, max_length=64)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('channel', models.CharField(choices=[('IN_APP', 'In-app'), ('EMAIL', 'Email')], max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AVAILABLE', 'Available'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('DEAD', 'Dead-letter')], default='PENDING', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['channel', 'status', 'next_retry_at'], name='notif_delivery_claim_idx')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'event_key', 'channel'), name='notification_delivery_once')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(max_length=64)),
                ('email_enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'event_code'), name='notification_preference_once')],
            },
        ),
    ]
