# Generated by Django 5.2.16 on 2026-07-15 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationdelivery_building'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('install_id', models.CharField(max_length=64)),
                ('fcm_token', models.CharField(max_length=512)),
                ('platform', models.CharField(choices=[('IOS', 'iOS'), ('ANDROID', 'Android')], max_length=16)),
                ('app_version', models.CharField(blank=True, max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'active'], name='device_user_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'install_id'), name='device_user_install_once'), models.UniqueConstraint(condition=models.Q(('active', True)), fields=('fcm_token',), name='device_active_fcm_token_once')],
            },
        ),
    ]
