# Generated by Django 5.2.16 on 2026-07-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='push_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='channel',
            field=models.CharField(choices=[('IN_APP', 'In-app'), ('EMAIL', 'Email'), ('PUSH', 'Push')], max_length=16),
        ),
    ]
