# Generated by Django 5.2.16 on 2026-07-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_push_channel_and_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdelivery',
            name='push_sent_device_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
