# Generated by Django 5.2.16 on 2026-07-23 12:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_registrationrequest'),
        ('notifications', '0005_push_sent_device_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(max_length=2000, validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('revision', models.PositiveIntegerField(default=1)),
                ('state', models.CharField(choices=[('PUBLISHED', 'Published'), ('WITHDRAWN', 'Withdrawn')], default='PUBLISHED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='accounts.building')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_announcements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
