# Generated by Django 5.2.16 on 2026-07-11 19:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('timezone', models.CharField(default='Asia/Ho_Chi_Minh', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(max_length=160)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('BOARD', 'Management Board'), ('OPERATOR', 'Property-management operator'), ('RESIDENT_REP', 'Resident representative'), ('AUDITOR', 'Auditor'), ('PLATFORM', 'Platform provider')], max_length=24)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.building')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.building')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentOccupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.unit')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OPERATOR', 'Operator'), ('MAINTENANCE', 'Maintenance'), ('BOARD', 'Board'), ('RESIDENT_REP', 'Resident representative'), ('AUDITOR', 'Auditor'), ('TECH_ADMIN', 'Technical administrator')], max_length=24)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'organization', 'role'), name='membership_once')],
            },
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('building', 'label'), name='unit_label_per_building'),
        ),
        migrations.RunSQL(
            """
            CREATE FUNCTION accounts_validate_membership_role()
            RETURNS trigger AS $$
            DECLARE
                organization_kind varchar;
            BEGIN
                SELECT kind INTO organization_kind
                FROM accounts_organization
                WHERE id = NEW.organization_id;

                IF NOT (
                    (NEW.role = 'BOARD' AND organization_kind = 'BOARD') OR
                    (NEW.role = 'RESIDENT_REP' AND organization_kind = 'RESIDENT_REP') OR
                    (NEW.role = 'AUDITOR' AND organization_kind = 'AUDITOR') OR
                    (NEW.role = 'TECH_ADMIN' AND organization_kind = 'PLATFORM') OR
                    (NEW.role IN ('OPERATOR', 'MAINTENANCE') AND organization_kind = 'OPERATOR')
                ) THEN
                    RAISE EXCEPTION 'membership role does not match organization kind'
                    USING ERRCODE = 'check_violation';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER accounts_membership_role_match
            BEFORE INSERT OR UPDATE OF organization_id, role
            ON accounts_organizationmembership
            FOR EACH ROW EXECUTE FUNCTION accounts_validate_membership_role();

            CREATE FUNCTION accounts_validate_organization_kind()
            RETURNS trigger AS $$
            BEGIN
                IF NEW.kind IS DISTINCT FROM OLD.kind AND EXISTS (
                    SELECT 1
                    FROM accounts_organizationmembership membership
                    WHERE membership.organization_id = OLD.id
                    AND NOT (
                        (membership.role = 'BOARD' AND NEW.kind = 'BOARD') OR
                        (membership.role = 'RESIDENT_REP' AND NEW.kind = 'RESIDENT_REP') OR
                        (membership.role = 'AUDITOR' AND NEW.kind = 'AUDITOR') OR
                        (membership.role = 'TECH_ADMIN' AND NEW.kind = 'PLATFORM') OR
                        (membership.role IN ('OPERATOR', 'MAINTENANCE') AND NEW.kind = 'OPERATOR')
                    )
                ) THEN
                    RAISE EXCEPTION 'organization kind does not match its memberships'
                    USING ERRCODE = 'check_violation';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER accounts_organization_kind_match
            BEFORE UPDATE OF kind
            ON accounts_organization
            FOR EACH ROW EXECUTE FUNCTION accounts_validate_organization_kind();
            """,
            """
            DROP TRIGGER accounts_organization_kind_match ON accounts_organization;
            DROP FUNCTION accounts_validate_organization_kind();
            DROP TRIGGER accounts_membership_role_match ON accounts_organizationmembership;
            DROP FUNCTION accounts_validate_membership_role();
            """,
        ),
    ]
