# Generated by Django 5.2.16 on 2026-07-13 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_grant_signed_executor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthThrottleBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_digest', models.CharField(db_index=True, max_length=64, unique=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('window_started_at', models.DateTimeField(blank=True, null=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BackupMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker_id', models.CharField(max_length=64, unique=True)),
                ('signed_at', models.DateTimeField()),
                ('signature', models.CharField(max_length=128)),
                ('storage_key', models.CharField(blank=True, max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BreakGlassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorizing_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorized_break_glass_sessions', to='accounts.organizationmembership')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='break_glass_sessions', to='accounts.organizationmembership')),
            ],
        ),
        migrations.CreateModel(
            name='BreakGlassRevocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('revoked_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='break_glass_revocations', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revocations', to='accounts.breakglasssession')),
            ],
        ),
    ]
