# Generated by Django 5.2.16 on 2026-07-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_security_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Canonical local form 0xxxxxxxxx; residents may log in with it.', max_length=20, null=True, unique=True),
        ),
    ]
