# Generated by Django 5.2.16 on 2026-07-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_phone'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('id', 'building'), name='unit_id_building_key'),
        ),
    ]
