# Generated by Django 5.2.16 on 2026-07-21 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_managementmembership'),
        ('evidence', '0010_outbox_building_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signerauthorizationrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.managementmembership'),
        ),
        migrations.AlterField(
            model_name='signerwallet',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.managementmembership'),
        ),
        migrations.AlterField(
            model_name='walletregistrationchallenge',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.managementmembership'),
        ),
    ]
