# Generated by Django 5.2.16 on 2026-07-21 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_management_wallet_procedures'),
        ('audit', '0003_alter_auditevent_membership'),
        ('finance', '0013_alter_acceptancerecord_membership_and_more'),
        ('maintenance', '0015_remove_workorder_work_order_emergency_request_identity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakglasssession',
            name='authorizing_membership',
        ),
        migrations.RemoveField(
            model_name='breakglasssession',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='capabilitygrant',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='building',
        ),
        migrations.RemoveField(
            model_name='organizationmembership',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organizationmembership',
            name='user',
        ),
        migrations.DeleteModel(
            name='BreakGlassRevocation',
        ),
        migrations.DeleteModel(
            name='BreakGlassSession',
        ),
        migrations.DeleteModel(
            name='CapabilityGrant',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='OrganizationMembership',
        ),
    ]
