# Generated by Django 5.2.16 on 2026-07-21 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_breakglasssession_authorizing_membership_and_more'),
        ('evidence', '0019_remove_blockchainoutboxevent_signer_wallet_and_more'),
        ('finance', '0023_remove_proposalversion_creator_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signerwallet',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='walletregistrationchallenge',
            name='membership',
        ),
        migrations.DeleteModel(
            name='SignerAuthorizationRequest',
        ),
        migrations.DeleteModel(
            name='SignerWallet',
        ),
        migrations.DeleteModel(
            name='WalletRegistrationChallenge',
        ),
    ]
