# Generated by Django 5.2.16 on 2026-07-23 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


REGISTRATION_UNIT_BUILDING_FK = """
ALTER TABLE accounts_registrationrequest
ADD CONSTRAINT registration_unit_building_fk
FOREIGN KEY (unit_id, building_id)
REFERENCES accounts_unit (id, building_id)
DEFERRABLE INITIALLY DEFERRED;
"""

DROP_REGISTRATION_UNIT_BUILDING_FK = """
ALTER TABLE accounts_registrationrequest
DROP CONSTRAINT IF EXISTS registration_unit_building_fk;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password_hash', models.CharField(blank=True, max_length=256)),
                ('status_token_digest', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=16)),
                ('rejection_reason', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.building')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_registration_requests', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.unit')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('phone',), name='unique_pending_registration_phone'), models.UniqueConstraint(condition=models.Q(('email__isnull', False), ('status', 'PENDING')), fields=('email',), name='unique_pending_registration_email')],
            },
        ),
        migrations.RunSQL(
            REGISTRATION_UNIT_BUILDING_FK,
            DROP_REGISTRATION_UNIT_BUILDING_FK,
        ),
    ]
